// <auto-generated />
namespace KP.Synchronization.ESAS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0-preview8-19405-04")]
    public sealed partial class foobar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(foobar));
        
        string IMigrationMetadata.Id
        {
            get { return "201909111229094_foobar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
