//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 03-03-2021 10:44:52
namespace esas.Dynamics.Models.Contracts
{
    /// <summary>
    /// There are no comments for AnsoegerSingle in the schema.
    /// </summary>
    public partial class AnsoegerSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Ansoeger>
    {
        /// <summary>
        /// Initialize a new AnsoegerSingle object.
        /// </summary>
        public AnsoegerSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new AnsoegerSingle object.
        /// </summary>
        public AnsoegerSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new AnsoegerSingle object.
        /// </summary>
        public AnsoegerSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Ansoeger> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for esas_postnummer_by in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.PostnummerSingle esas_postnummer_by
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._esas_postnummer_by == null))
                {
                    this._esas_postnummer_by = new global::esas.Dynamics.Models.Contracts.PostnummerSingle(this.Context, GetPath("esas_postnummer_by"));
                }
                return this._esas_postnummer_by;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.PostnummerSingle _esas_postnummer_by;
        /// <summary>
        /// There are no comments for esas_statsborgerskab in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.LandSingle esas_statsborgerskab
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._esas_statsborgerskab == null))
                {
                    this._esas_statsborgerskab = new global::esas.Dynamics.Models.Contracts.LandSingle(this.Context, GetPath("esas_statsborgerskab"));
                }
                return this._esas_statsborgerskab;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.LandSingle _esas_statsborgerskab;
        /// <summary>
        /// There are no comments for esas_land in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.LandSingle esas_land
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._esas_land == null))
                {
                    this._esas_land = new global::esas.Dynamics.Models.Contracts.LandSingle(this.Context, GetPath("esas_land"));
                }
                return this._esas_land;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.LandSingle _esas_land;
        /// <summary>
        /// There are no comments for list_esas_ansoegning in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.Ansoegning> list_esas_ansoegning
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._list_esas_ansoegning == null))
                {
                    this._list_esas_ansoegning = Context.CreateQuery<global::esas.Dynamics.Models.Contracts.Ansoegning>(GetPath("list_esas_ansoegning"));
                }
                return this._list_esas_ansoegning;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.Ansoegning> _list_esas_ansoegning;
    }
    /// <summary>
    /// There are no comments for Ansoeger in the schema.
    /// </summary>
    /// <KeyProperties>
    /// LeadId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("LeadId")]
    public partial class Ansoeger : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property LeadId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> LeadId
        {
            get
            {
                return this._LeadId;
            }
            set
            {
                this.OnLeadIdChanging(value);
                this._LeadId = value;
                this.OnLeadIdChanged();
                this.OnPropertyChanged("LeadId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _LeadId;
        partial void OnLeadIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnLeadIdChanged();
        /// <summary>
        /// There are no comments for Property esas_postnummer_by_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_postnummer_by_id
        {
            get
            {
                return this._esas_postnummer_by_id;
            }
            set
            {
                this.Onesas_postnummer_by_idChanging(value);
                this._esas_postnummer_by_id = value;
                this.Onesas_postnummer_by_idChanged();
                this.OnPropertyChanged("esas_postnummer_by_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_postnummer_by_id;
        partial void Onesas_postnummer_by_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_postnummer_by_idChanged();
        /// <summary>
        /// There are no comments for Property esas_statsborgerskab_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_statsborgerskab_id
        {
            get
            {
                return this._esas_statsborgerskab_id;
            }
            set
            {
                this.Onesas_statsborgerskab_idChanging(value);
                this._esas_statsborgerskab_id = value;
                this.Onesas_statsborgerskab_idChanged();
                this.OnPropertyChanged("esas_statsborgerskab_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_statsborgerskab_id;
        partial void Onesas_statsborgerskab_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_statsborgerskab_idChanged();
        /// <summary>
        /// There are no comments for Property esas_land_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_land_id
        {
            get
            {
                return this._esas_land_id;
            }
            set
            {
                this.Onesas_land_idChanging(value);
                this._esas_land_id = value;
                this.Onesas_land_idChanged();
                this.OnPropertyChanged("esas_land_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_land_id;
        partial void Onesas_land_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_land_idChanged();
        /// <summary>
        /// There are no comments for Property FullName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string FullName
        {
            get
            {
                return this._FullName;
            }
            set
            {
                this.OnFullNameChanging(value);
                this._FullName = value;
                this.OnFullNameChanged();
                this.OnPropertyChanged("FullName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _FullName;
        partial void OnFullNameChanging(string value);
        partial void OnFullNameChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property MiddleName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string MiddleName
        {
            get
            {
                return this._MiddleName;
            }
            set
            {
                this.OnMiddleNameChanging(value);
                this._MiddleName = value;
                this.OnMiddleNameChanged();
                this.OnPropertyChanged("MiddleName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _MiddleName;
        partial void OnMiddleNameChanging(string value);
        partial void OnMiddleNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property Address1_Line1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Address1_Line1
        {
            get
            {
                return this._Address1_Line1;
            }
            set
            {
                this.OnAddress1_Line1Changing(value);
                this._Address1_Line1 = value;
                this.OnAddress1_Line1Changed();
                this.OnPropertyChanged("Address1_Line1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Address1_Line1;
        partial void OnAddress1_Line1Changing(string value);
        partial void OnAddress1_Line1Changed();
        /// <summary>
        /// There are no comments for Property Address1_Line2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Address1_Line2
        {
            get
            {
                return this._Address1_Line2;
            }
            set
            {
                this.OnAddress1_Line2Changing(value);
                this._Address1_Line2 = value;
                this.OnAddress1_Line2Changed();
                this.OnPropertyChanged("Address1_Line2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Address1_Line2;
        partial void OnAddress1_Line2Changing(string value);
        partial void OnAddress1_Line2Changed();
        /// <summary>
        /// There are no comments for Property EmailAddress1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string EmailAddress1
        {
            get
            {
                return this._EmailAddress1;
            }
            set
            {
                this.OnEmailAddress1Changing(value);
                this._EmailAddress1 = value;
                this.OnEmailAddress1Changed();
                this.OnPropertyChanged("EmailAddress1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _EmailAddress1;
        partial void OnEmailAddress1Changing(string value);
        partial void OnEmailAddress1Changed();
        /// <summary>
        /// There are no comments for Property esas_alternativt_cpr_nummer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_alternativt_cpr_nummer
        {
            get
            {
                return this._esas_alternativt_cpr_nummer;
            }
            set
            {
                this.Onesas_alternativt_cpr_nummerChanging(value);
                this._esas_alternativt_cpr_nummer = value;
                this.Onesas_alternativt_cpr_nummerChanged();
                this.OnPropertyChanged("esas_alternativt_cpr_nummer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_alternativt_cpr_nummer;
        partial void Onesas_alternativt_cpr_nummerChanging(string value);
        partial void Onesas_alternativt_cpr_nummerChanged();
        /// <summary>
        /// There are no comments for Property esas_cpr_nummer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_cpr_nummer
        {
            get
            {
                return this._esas_cpr_nummer;
            }
            set
            {
                this.Onesas_cpr_nummerChanging(value);
                this._esas_cpr_nummer = value;
                this.Onesas_cpr_nummerChanged();
                this.OnPropertyChanged("esas_cpr_nummer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_cpr_nummer;
        partial void Onesas_cpr_nummerChanging(string value);
        partial void Onesas_cpr_nummerChanged();
        /// <summary>
        /// There are no comments for Property esas_eidas_pid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_eidas_pid
        {
            get
            {
                return this._esas_eidas_pid;
            }
            set
            {
                this.Onesas_eidas_pidChanging(value);
                this._esas_eidas_pid = value;
                this.Onesas_eidas_pidChanged();
                this.OnPropertyChanged("esas_eidas_pid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_eidas_pid;
        partial void Onesas_eidas_pidChanging(string value);
        partial void Onesas_eidas_pidChanged();
        /// <summary>
        /// There are no comments for Property esas_cpr_personstatus in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> esas_cpr_personstatus
        {
            get
            {
                return this._esas_cpr_personstatus;
            }
            set
            {
                this.Onesas_cpr_personstatusChanging(value);
                this._esas_cpr_personstatus = value;
                this.Onesas_cpr_personstatusChanged();
                this.OnPropertyChanged("esas_cpr_personstatus");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _esas_cpr_personstatus;
        partial void Onesas_cpr_personstatusChanging(global::System.Nullable<int> value);
        partial void Onesas_cpr_personstatusChanged();
        /// <summary>
        /// There are no comments for Property esas_koen in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> esas_koen
        {
            get
            {
                return this._esas_koen;
            }
            set
            {
                this.Onesas_koenChanging(value);
                this._esas_koen = value;
                this.Onesas_koenChanged();
                this.OnPropertyChanged("esas_koen");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _esas_koen;
        partial void Onesas_koenChanging(global::System.Nullable<int> value);
        partial void Onesas_koenChanged();
        /// <summary>
        /// There are no comments for Property Telephone1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Telephone1
        {
            get
            {
                return this._Telephone1;
            }
            set
            {
                this.OnTelephone1Changing(value);
                this._Telephone1 = value;
                this.OnTelephone1Changed();
                this.OnPropertyChanged("Telephone1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Telephone1;
        partial void OnTelephone1Changing(string value);
        partial void OnTelephone1Changed();
        /// <summary>
        /// There are no comments for Property MobilePhone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string MobilePhone
        {
            get
            {
                return this._MobilePhone;
            }
            set
            {
                this.OnMobilePhoneChanging(value);
                this._MobilePhone = value;
                this.OnMobilePhoneChanged();
                this.OnPropertyChanged("MobilePhone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _MobilePhone;
        partial void OnMobilePhoneChanging(string value);
        partial void OnMobilePhoneChanged();
        /// <summary>
        /// There are no comments for Property esas_navne_adressebeskyttet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<bool> esas_navne_adressebeskyttet
        {
            get
            {
                return this._esas_navne_adressebeskyttet;
            }
            set
            {
                this.Onesas_navne_adressebeskyttetChanging(value);
                this._esas_navne_adressebeskyttet = value;
                this.Onesas_navne_adressebeskyttetChanged();
                this.OnPropertyChanged("esas_navne_adressebeskyttet");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _esas_navne_adressebeskyttet;
        partial void Onesas_navne_adressebeskyttetChanging(global::System.Nullable<bool> value);
        partial void Onesas_navne_adressebeskyttetChanged();
        /// <summary>
        /// There are no comments for Property esas_optagelse_dk_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_optagelse_dk_id
        {
            get
            {
                return this._esas_optagelse_dk_id;
            }
            set
            {
                this.Onesas_optagelse_dk_idChanging(value);
                this._esas_optagelse_dk_id = value;
                this.Onesas_optagelse_dk_idChanged();
                this.OnPropertyChanged("esas_optagelse_dk_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_optagelse_dk_id;
        partial void Onesas_optagelse_dk_idChanging(string value);
        partial void Onesas_optagelse_dk_idChanged();
        /// <summary>
        /// There are no comments for Property esas_foedselsdato in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> esas_foedselsdato
        {
            get
            {
                return this._esas_foedselsdato;
            }
            set
            {
                this.Onesas_foedselsdatoChanging(value);
                this._esas_foedselsdato = value;
                this.Onesas_foedselsdatoChanged();
                this.OnPropertyChanged("esas_foedselsdato");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _esas_foedselsdato;
        partial void Onesas_foedselsdatoChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void Onesas_foedselsdatoChanged();
        /// <summary>
        /// There are no comments for Property esas_cpr_seneste_opdatering in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> esas_cpr_seneste_opdatering
        {
            get
            {
                return this._esas_cpr_seneste_opdatering;
            }
            set
            {
                this.Onesas_cpr_seneste_opdateringChanging(value);
                this._esas_cpr_seneste_opdatering = value;
                this.Onesas_cpr_seneste_opdateringChanged();
                this.OnPropertyChanged("esas_cpr_seneste_opdatering");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _esas_cpr_seneste_opdatering;
        partial void Onesas_cpr_seneste_opdateringChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void Onesas_cpr_seneste_opdateringChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _CreatedBy;
        partial void OnCreatedByChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property CreatedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> CreatedOn
        {
            get
            {
                return this._CreatedOn;
            }
            set
            {
                this.OnCreatedOnChanging(value);
                this._CreatedOn = value;
                this.OnCreatedOnChanged();
                this.OnPropertyChanged("CreatedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _CreatedOn;
        partial void OnCreatedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedOnChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _ModifiedBy;
        partial void OnModifiedByChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> ModifiedOn
        {
            get
            {
                return this._ModifiedOn;
            }
            set
            {
                this.OnModifiedOnChanging(value);
                this._ModifiedOn = value;
                this.OnModifiedOnChanged();
                this.OnPropertyChanged("ModifiedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _ModifiedOn;
        partial void OnModifiedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedOnChanged();
        /// <summary>
        /// There are no comments for Property OwningBusinessUnit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> OwningBusinessUnit
        {
            get
            {
                return this._OwningBusinessUnit;
            }
            set
            {
                this.OnOwningBusinessUnitChanging(value);
                this._OwningBusinessUnit = value;
                this.OnOwningBusinessUnitChanged();
                this.OnPropertyChanged("OwningBusinessUnit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _OwningBusinessUnit;
        partial void OnOwningBusinessUnitChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnOwningBusinessUnitChanged();
        /// <summary>
        /// There are no comments for Property statecode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> statecode
        {
            get
            {
                return this._statecode;
            }
            set
            {
                this.OnstatecodeChanging(value);
                this._statecode = value;
                this.OnstatecodeChanged();
                this.OnPropertyChanged("statecode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _statecode;
        partial void OnstatecodeChanging(global::System.Nullable<int> value);
        partial void OnstatecodeChanged();
        /// <summary>
        /// There are no comments for Property statuscode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> statuscode
        {
            get
            {
                return this._statuscode;
            }
            set
            {
                this.OnstatuscodeChanging(value);
                this._statuscode = value;
                this.OnstatuscodeChanged();
                this.OnPropertyChanged("statuscode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _statuscode;
        partial void OnstatuscodeChanging(global::System.Nullable<int> value);
        partial void OnstatuscodeChanged();
        /// <summary>
        /// There are no comments for Property esas_postnummer_by in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.Postnummer esas_postnummer_by
        {
            get
            {
                return this._esas_postnummer_by;
            }
            set
            {
                this.Onesas_postnummer_byChanging(value);
                this._esas_postnummer_by = value;
                this.Onesas_postnummer_byChanged();
                this.OnPropertyChanged("esas_postnummer_by");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.Postnummer _esas_postnummer_by;
        partial void Onesas_postnummer_byChanging(global::esas.Dynamics.Models.Contracts.Postnummer value);
        partial void Onesas_postnummer_byChanged();
        /// <summary>
        /// There are no comments for Property esas_statsborgerskab in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.Land esas_statsborgerskab
        {
            get
            {
                return this._esas_statsborgerskab;
            }
            set
            {
                this.Onesas_statsborgerskabChanging(value);
                this._esas_statsborgerskab = value;
                this.Onesas_statsborgerskabChanged();
                this.OnPropertyChanged("esas_statsborgerskab");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.Land _esas_statsborgerskab;
        partial void Onesas_statsborgerskabChanging(global::esas.Dynamics.Models.Contracts.Land value);
        partial void Onesas_statsborgerskabChanged();
        /// <summary>
        /// There are no comments for Property esas_land in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.Land esas_land
        {
            get
            {
                return this._esas_land;
            }
            set
            {
                this.Onesas_landChanging(value);
                this._esas_land = value;
                this.Onesas_landChanged();
                this.OnPropertyChanged("esas_land");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.Land _esas_land;
        partial void Onesas_landChanging(global::esas.Dynamics.Models.Contracts.Land value);
        partial void Onesas_landChanged();
        /// <summary>
        /// There are no comments for Property list_esas_ansoegning in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Ansoegning> list_esas_ansoegning
        {
            get
            {
                return this._list_esas_ansoegning;
            }
            set
            {
                this.Onlist_esas_ansoegningChanging(value);
                this._list_esas_ansoegning = value;
                this.Onlist_esas_ansoegningChanged();
                this.OnPropertyChanged("list_esas_ansoegning");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Ansoegning> _list_esas_ansoegning = new global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Ansoegning>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void Onlist_esas_ansoegningChanging(global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Ansoegning> value);
        partial void Onlist_esas_ansoegningChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
