//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 03-03-2021 10:44:52
namespace esas.Dynamics.Models.Contracts
{
    /// <summary>
    /// There are no comments for BedoemmelsesrundeSingle in the schema.
    /// </summary>
    public partial class BedoemmelsesrundeSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Bedoemmelsesrunde>
    {
        /// <summary>
        /// Initialize a new BedoemmelsesrundeSingle object.
        /// </summary>
        public BedoemmelsesrundeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new BedoemmelsesrundeSingle object.
        /// </summary>
        public BedoemmelsesrundeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new BedoemmelsesrundeSingle object.
        /// </summary>
        public BedoemmelsesrundeSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Bedoemmelsesrunde> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for esas_planlaegningsuddannelseselement in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.PlanlaegningsUddannelseselementSingle esas_planlaegningsuddannelseselement
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._esas_planlaegningsuddannelseselement == null))
                {
                    this._esas_planlaegningsuddannelseselement = new global::esas.Dynamics.Models.Contracts.PlanlaegningsUddannelseselementSingle(this.Context, GetPath("esas_planlaegningsuddannelseselement"));
                }
                return this._esas_planlaegningsuddannelseselement;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.PlanlaegningsUddannelseselementSingle _esas_planlaegningsuddannelseselement;
        /// <summary>
        /// There are no comments for esas_omraadeopsaetning in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.OmraadenummeropsaetningSingle esas_omraadeopsaetning
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._esas_omraadeopsaetning == null))
                {
                    this._esas_omraadeopsaetning = new global::esas.Dynamics.Models.Contracts.OmraadenummeropsaetningSingle(this.Context, GetPath("esas_omraadeopsaetning"));
                }
                return this._esas_omraadeopsaetning;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.OmraadenummeropsaetningSingle _esas_omraadeopsaetning;
        /// <summary>
        /// There are no comments for esas_omraadespecialisering in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.OmraadespecialiseringSingle esas_omraadespecialisering
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._esas_omraadespecialisering == null))
                {
                    this._esas_omraadespecialisering = new global::esas.Dynamics.Models.Contracts.OmraadespecialiseringSingle(this.Context, GetPath("esas_omraadespecialisering"));
                }
                return this._esas_omraadespecialisering;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.OmraadespecialiseringSingle _esas_omraadespecialisering;
        /// <summary>
        /// There are no comments for list_esas_bedoemmelse in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.Bedoemmelse> list_esas_bedoemmelse
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._list_esas_bedoemmelse == null))
                {
                    this._list_esas_bedoemmelse = Context.CreateQuery<global::esas.Dynamics.Models.Contracts.Bedoemmelse>(GetPath("list_esas_bedoemmelse"));
                }
                return this._list_esas_bedoemmelse;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.Bedoemmelse> _list_esas_bedoemmelse;
    }
    /// <summary>
    /// There are no comments for Bedoemmelsesrunde in the schema.
    /// </summary>
    /// <KeyProperties>
    /// esas_bedoemmelsesrundeId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("esas_bedoemmelsesrundeId")]
    public partial class Bedoemmelsesrunde : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property esas_bedoemmelsesrundeId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_bedoemmelsesrundeId
        {
            get
            {
                return this._esas_bedoemmelsesrundeId;
            }
            set
            {
                this.Onesas_bedoemmelsesrundeIdChanging(value);
                this._esas_bedoemmelsesrundeId = value;
                this.Onesas_bedoemmelsesrundeIdChanged();
                this.OnPropertyChanged("esas_bedoemmelsesrundeId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_bedoemmelsesrundeId;
        partial void Onesas_bedoemmelsesrundeIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_bedoemmelsesrundeIdChanged();
        /// <summary>
        /// There are no comments for Property esas_planlaegningsuddannelseselement_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_planlaegningsuddannelseselement_id
        {
            get
            {
                return this._esas_planlaegningsuddannelseselement_id;
            }
            set
            {
                this.Onesas_planlaegningsuddannelseselement_idChanging(value);
                this._esas_planlaegningsuddannelseselement_id = value;
                this.Onesas_planlaegningsuddannelseselement_idChanged();
                this.OnPropertyChanged("esas_planlaegningsuddannelseselement_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_planlaegningsuddannelseselement_id;
        partial void Onesas_planlaegningsuddannelseselement_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_planlaegningsuddannelseselement_idChanged();
        /// <summary>
        /// There are no comments for Property esas_omraadeopsaetning_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_omraadeopsaetning_id
        {
            get
            {
                return this._esas_omraadeopsaetning_id;
            }
            set
            {
                this.Onesas_omraadeopsaetning_idChanging(value);
                this._esas_omraadeopsaetning_id = value;
                this.Onesas_omraadeopsaetning_idChanged();
                this.OnPropertyChanged("esas_omraadeopsaetning_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_omraadeopsaetning_id;
        partial void Onesas_omraadeopsaetning_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_omraadeopsaetning_idChanged();
        /// <summary>
        /// There are no comments for Property esas_omraadespecialisering_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_omraadespecialisering_id
        {
            get
            {
                return this._esas_omraadespecialisering_id;
            }
            set
            {
                this.Onesas_omraadespecialisering_idChanging(value);
                this._esas_omraadespecialisering_id = value;
                this.Onesas_omraadespecialisering_idChanged();
                this.OnPropertyChanged("esas_omraadespecialisering_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_omraadespecialisering_id;
        partial void Onesas_omraadespecialisering_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_omraadespecialisering_idChanged();
        /// <summary>
        /// There are no comments for Property esas_navn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_navn
        {
            get
            {
                return this._esas_navn;
            }
            set
            {
                this.Onesas_navnChanging(value);
                this._esas_navn = value;
                this.Onesas_navnChanged();
                this.OnPropertyChanged("esas_navn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_navn;
        partial void Onesas_navnChanging(string value);
        partial void Onesas_navnChanged();
        /// <summary>
        /// There are no comments for Property esas_nummer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_nummer
        {
            get
            {
                return this._esas_nummer;
            }
            set
            {
                this.Onesas_nummerChanging(value);
                this._esas_nummer = value;
                this.Onesas_nummerChanged();
                this.OnPropertyChanged("esas_nummer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_nummer;
        partial void Onesas_nummerChanging(string value);
        partial void Onesas_nummerChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _CreatedBy;
        partial void OnCreatedByChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property CreatedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> CreatedOn
        {
            get
            {
                return this._CreatedOn;
            }
            set
            {
                this.OnCreatedOnChanging(value);
                this._CreatedOn = value;
                this.OnCreatedOnChanged();
                this.OnPropertyChanged("CreatedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _CreatedOn;
        partial void OnCreatedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedOnChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _ModifiedBy;
        partial void OnModifiedByChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> ModifiedOn
        {
            get
            {
                return this._ModifiedOn;
            }
            set
            {
                this.OnModifiedOnChanging(value);
                this._ModifiedOn = value;
                this.OnModifiedOnChanged();
                this.OnPropertyChanged("ModifiedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _ModifiedOn;
        partial void OnModifiedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedOnChanged();
        /// <summary>
        /// There are no comments for Property OwningBusinessUnit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> OwningBusinessUnit
        {
            get
            {
                return this._OwningBusinessUnit;
            }
            set
            {
                this.OnOwningBusinessUnitChanging(value);
                this._OwningBusinessUnit = value;
                this.OnOwningBusinessUnitChanged();
                this.OnPropertyChanged("OwningBusinessUnit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _OwningBusinessUnit;
        partial void OnOwningBusinessUnitChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnOwningBusinessUnitChanged();
        /// <summary>
        /// There are no comments for Property statecode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> statecode
        {
            get
            {
                return this._statecode;
            }
            set
            {
                this.OnstatecodeChanging(value);
                this._statecode = value;
                this.OnstatecodeChanged();
                this.OnPropertyChanged("statecode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _statecode;
        partial void OnstatecodeChanging(global::System.Nullable<int> value);
        partial void OnstatecodeChanged();
        /// <summary>
        /// There are no comments for Property statuscode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> statuscode
        {
            get
            {
                return this._statuscode;
            }
            set
            {
                this.OnstatuscodeChanging(value);
                this._statuscode = value;
                this.OnstatuscodeChanged();
                this.OnPropertyChanged("statuscode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _statuscode;
        partial void OnstatuscodeChanging(global::System.Nullable<int> value);
        partial void OnstatuscodeChanged();
        /// <summary>
        /// There are no comments for Property esas_planlaegningsuddannelseselement in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.PlanlaegningsUddannelseselement esas_planlaegningsuddannelseselement
        {
            get
            {
                return this._esas_planlaegningsuddannelseselement;
            }
            set
            {
                this.Onesas_planlaegningsuddannelseselementChanging(value);
                this._esas_planlaegningsuddannelseselement = value;
                this.Onesas_planlaegningsuddannelseselementChanged();
                this.OnPropertyChanged("esas_planlaegningsuddannelseselement");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.PlanlaegningsUddannelseselement _esas_planlaegningsuddannelseselement;
        partial void Onesas_planlaegningsuddannelseselementChanging(global::esas.Dynamics.Models.Contracts.PlanlaegningsUddannelseselement value);
        partial void Onesas_planlaegningsuddannelseselementChanged();
        /// <summary>
        /// There are no comments for Property esas_omraadeopsaetning in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.Omraadenummeropsaetning esas_omraadeopsaetning
        {
            get
            {
                return this._esas_omraadeopsaetning;
            }
            set
            {
                this.Onesas_omraadeopsaetningChanging(value);
                this._esas_omraadeopsaetning = value;
                this.Onesas_omraadeopsaetningChanged();
                this.OnPropertyChanged("esas_omraadeopsaetning");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.Omraadenummeropsaetning _esas_omraadeopsaetning;
        partial void Onesas_omraadeopsaetningChanging(global::esas.Dynamics.Models.Contracts.Omraadenummeropsaetning value);
        partial void Onesas_omraadeopsaetningChanged();
        /// <summary>
        /// There are no comments for Property esas_omraadespecialisering in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.Omraadespecialisering esas_omraadespecialisering
        {
            get
            {
                return this._esas_omraadespecialisering;
            }
            set
            {
                this.Onesas_omraadespecialiseringChanging(value);
                this._esas_omraadespecialisering = value;
                this.Onesas_omraadespecialiseringChanged();
                this.OnPropertyChanged("esas_omraadespecialisering");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.Omraadespecialisering _esas_omraadespecialisering;
        partial void Onesas_omraadespecialiseringChanging(global::esas.Dynamics.Models.Contracts.Omraadespecialisering value);
        partial void Onesas_omraadespecialiseringChanged();
        /// <summary>
        /// There are no comments for Property list_esas_bedoemmelse in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Bedoemmelse> list_esas_bedoemmelse
        {
            get
            {
                return this._list_esas_bedoemmelse;
            }
            set
            {
                this.Onlist_esas_bedoemmelseChanging(value);
                this._list_esas_bedoemmelse = value;
                this.Onlist_esas_bedoemmelseChanged();
                this.OnPropertyChanged("list_esas_bedoemmelse");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Bedoemmelse> _list_esas_bedoemmelse = new global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Bedoemmelse>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void Onlist_esas_bedoemmelseChanging(global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Bedoemmelse> value);
        partial void Onlist_esas_bedoemmelseChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
