//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 03-03-2021 10:44:52
namespace esas.Dynamics.Models.Contracts
{
    /// <summary>
    /// There are no comments for GennemfoerelsesUddannelseselementSingle in the schema.
    /// </summary>
    public partial class GennemfoerelsesUddannelseselementSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<GennemfoerelsesUddannelseselement>
    {
        /// <summary>
        /// Initialize a new GennemfoerelsesUddannelseselementSingle object.
        /// </summary>
        public GennemfoerelsesUddannelseselementSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new GennemfoerelsesUddannelseselementSingle object.
        /// </summary>
        public GennemfoerelsesUddannelseselementSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new GennemfoerelsesUddannelseselementSingle object.
        /// </summary>
        public GennemfoerelsesUddannelseselementSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<GennemfoerelsesUddannelseselement> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for esas_pue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.PlanlaegningsUddannelseselementSingle esas_pue
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._esas_pue == null))
                {
                    this._esas_pue = new global::esas.Dynamics.Models.Contracts.PlanlaegningsUddannelseselementSingle(this.Context, GetPath("esas_pue"));
                }
                return this._esas_pue;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.PlanlaegningsUddannelseselementSingle _esas_pue;
        /// <summary>
        /// There are no comments for esas_uddannelseselement in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.StruktureltUddannelseselementSingle esas_uddannelseselement
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._esas_uddannelseselement == null))
                {
                    this._esas_uddannelseselement = new global::esas.Dynamics.Models.Contracts.StruktureltUddannelseselementSingle(this.Context, GetPath("esas_uddannelseselement"));
                }
                return this._esas_uddannelseselement;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.StruktureltUddannelseselementSingle _esas_uddannelseselement;
        /// <summary>
        /// There are no comments for esas_studieforloeb in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.StudieforloebSingle esas_studieforloeb
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._esas_studieforloeb == null))
                {
                    this._esas_studieforloeb = new global::esas.Dynamics.Models.Contracts.StudieforloebSingle(this.Context, GetPath("esas_studieforloeb"));
                }
                return this._esas_studieforloeb;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.StudieforloebSingle _esas_studieforloeb;
        /// <summary>
        /// There are no comments for esas_hold in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.HoldSingle esas_hold
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._esas_hold == null))
                {
                    this._esas_hold = new global::esas.Dynamics.Models.Contracts.HoldSingle(this.Context, GetPath("esas_hold"));
                }
                return this._esas_hold;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.HoldSingle _esas_hold;
        /// <summary>
        /// There are no comments for esas_bedoemmelsesresultat in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.KarakterSingle esas_bedoemmelsesresultat
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._esas_bedoemmelsesresultat == null))
                {
                    this._esas_bedoemmelsesresultat = new global::esas.Dynamics.Models.Contracts.KarakterSingle(this.Context, GetPath("esas_bedoemmelsesresultat"));
                }
                return this._esas_bedoemmelsesresultat;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.KarakterSingle _esas_bedoemmelsesresultat;
        /// <summary>
        /// There are no comments for esas_aktivitetsafdeling in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.AfdelingSingle esas_aktivitetsafdeling
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._esas_aktivitetsafdeling == null))
                {
                    this._esas_aktivitetsafdeling = new global::esas.Dynamics.Models.Contracts.AfdelingSingle(this.Context, GetPath("esas_aktivitetsafdeling"));
                }
                return this._esas_aktivitetsafdeling;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.AfdelingSingle _esas_aktivitetsafdeling;
        /// <summary>
        /// There are no comments for esas_udbud_af_valgfag in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.StruktureltUddannelseselementSingle esas_udbud_af_valgfag
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._esas_udbud_af_valgfag == null))
                {
                    this._esas_udbud_af_valgfag = new global::esas.Dynamics.Models.Contracts.StruktureltUddannelseselementSingle(this.Context, GetPath("esas_udbud_af_valgfag"));
                }
                return this._esas_udbud_af_valgfag;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.StruktureltUddannelseselementSingle _esas_udbud_af_valgfag;
        /// <summary>
        /// There are no comments for list_esas_praktikophold in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.Praktikophold> list_esas_praktikophold
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._list_esas_praktikophold == null))
                {
                    this._list_esas_praktikophold = Context.CreateQuery<global::esas.Dynamics.Models.Contracts.Praktikophold>(GetPath("list_esas_praktikophold"));
                }
                return this._list_esas_praktikophold;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.Praktikophold> _list_esas_praktikophold;
        /// <summary>
        /// There are no comments for list_esas_bedoemmelse in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.Bedoemmelse> list_esas_bedoemmelse
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._list_esas_bedoemmelse == null))
                {
                    this._list_esas_bedoemmelse = Context.CreateQuery<global::esas.Dynamics.Models.Contracts.Bedoemmelse>(GetPath("list_esas_bedoemmelse"));
                }
                return this._list_esas_bedoemmelse;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.Bedoemmelse> _list_esas_bedoemmelse;
        /// <summary>
        /// There are no comments for list_esas_meritregistrering in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.MeritRegistrering> list_esas_meritregistrering
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._list_esas_meritregistrering == null))
                {
                    this._list_esas_meritregistrering = Context.CreateQuery<global::esas.Dynamics.Models.Contracts.MeritRegistrering>(GetPath("list_esas_meritregistrering"));
                }
                return this._list_esas_meritregistrering;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.MeritRegistrering> _list_esas_meritregistrering;
    }
    /// <summary>
    /// There are no comments for GennemfoerelsesUddannelseselement in the schema.
    /// </summary>
    /// <KeyProperties>
    /// esas_uddannelseselement_gennemfoerelseId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("esas_uddannelseselement_gennemfoerelseId")]
    public partial class GennemfoerelsesUddannelseselement : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new GennemfoerelsesUddannelseselement object.
        /// </summary>
        /// <param name="esas_semester_nummer">Initial value of esas_semester_nummer.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static GennemfoerelsesUddannelseselement CreateGennemfoerelsesUddannelseselement(int esas_semester_nummer)
        {
            GennemfoerelsesUddannelseselement gennemfoerelsesUddannelseselement = new GennemfoerelsesUddannelseselement();
            gennemfoerelsesUddannelseselement.esas_semester_nummer = esas_semester_nummer;
            return gennemfoerelsesUddannelseselement;
        }
        /// <summary>
        /// There are no comments for Property esas_uddannelseselement_gennemfoerelseId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_uddannelseselement_gennemfoerelseId
        {
            get
            {
                return this._esas_uddannelseselement_gennemfoerelseId;
            }
            set
            {
                this.Onesas_uddannelseselement_gennemfoerelseIdChanging(value);
                this._esas_uddannelseselement_gennemfoerelseId = value;
                this.Onesas_uddannelseselement_gennemfoerelseIdChanged();
                this.OnPropertyChanged("esas_uddannelseselement_gennemfoerelseId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_uddannelseselement_gennemfoerelseId;
        partial void Onesas_uddannelseselement_gennemfoerelseIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_uddannelseselement_gennemfoerelseIdChanged();
        /// <summary>
        /// There are no comments for Property esas_pue_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_pue_id
        {
            get
            {
                return this._esas_pue_id;
            }
            set
            {
                this.Onesas_pue_idChanging(value);
                this._esas_pue_id = value;
                this.Onesas_pue_idChanged();
                this.OnPropertyChanged("esas_pue_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_pue_id;
        partial void Onesas_pue_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_pue_idChanged();
        /// <summary>
        /// There are no comments for Property esas_uddannelseselement_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_uddannelseselement_id
        {
            get
            {
                return this._esas_uddannelseselement_id;
            }
            set
            {
                this.Onesas_uddannelseselement_idChanging(value);
                this._esas_uddannelseselement_id = value;
                this.Onesas_uddannelseselement_idChanged();
                this.OnPropertyChanged("esas_uddannelseselement_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_uddannelseselement_id;
        partial void Onesas_uddannelseselement_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_uddannelseselement_idChanged();
        /// <summary>
        /// There are no comments for Property esas_studieforloeb_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_studieforloeb_id
        {
            get
            {
                return this._esas_studieforloeb_id;
            }
            set
            {
                this.Onesas_studieforloeb_idChanging(value);
                this._esas_studieforloeb_id = value;
                this.Onesas_studieforloeb_idChanged();
                this.OnPropertyChanged("esas_studieforloeb_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_studieforloeb_id;
        partial void Onesas_studieforloeb_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_studieforloeb_idChanged();
        /// <summary>
        /// There are no comments for Property esas_hold_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_hold_id
        {
            get
            {
                return this._esas_hold_id;
            }
            set
            {
                this.Onesas_hold_idChanging(value);
                this._esas_hold_id = value;
                this.Onesas_hold_idChanged();
                this.OnPropertyChanged("esas_hold_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_hold_id;
        partial void Onesas_hold_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_hold_idChanged();
        /// <summary>
        /// There are no comments for Property esas_bedoemmelsesresultat_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_bedoemmelsesresultat_id
        {
            get
            {
                return this._esas_bedoemmelsesresultat_id;
            }
            set
            {
                this.Onesas_bedoemmelsesresultat_idChanging(value);
                this._esas_bedoemmelsesresultat_id = value;
                this.Onesas_bedoemmelsesresultat_idChanged();
                this.OnPropertyChanged("esas_bedoemmelsesresultat_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_bedoemmelsesresultat_id;
        partial void Onesas_bedoemmelsesresultat_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_bedoemmelsesresultat_idChanged();
        /// <summary>
        /// There are no comments for Property esas_aktivitetsafdeling_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_aktivitetsafdeling_id
        {
            get
            {
                return this._esas_aktivitetsafdeling_id;
            }
            set
            {
                this.Onesas_aktivitetsafdeling_idChanging(value);
                this._esas_aktivitetsafdeling_id = value;
                this.Onesas_aktivitetsafdeling_idChanged();
                this.OnPropertyChanged("esas_aktivitetsafdeling_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_aktivitetsafdeling_id;
        partial void Onesas_aktivitetsafdeling_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_aktivitetsafdeling_idChanged();
        /// <summary>
        /// There are no comments for Property esas_udbud_af_valgfag_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_udbud_af_valgfag_id
        {
            get
            {
                return this._esas_udbud_af_valgfag_id;
            }
            set
            {
                this.Onesas_udbud_af_valgfag_idChanging(value);
                this._esas_udbud_af_valgfag_id = value;
                this.Onesas_udbud_af_valgfag_idChanged();
                this.OnPropertyChanged("esas_udbud_af_valgfag_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_udbud_af_valgfag_id;
        partial void Onesas_udbud_af_valgfag_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_udbud_af_valgfag_idChanged();
        /// <summary>
        /// There are no comments for Property esas_antal_forsoeg in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> esas_antal_forsoeg
        {
            get
            {
                return this._esas_antal_forsoeg;
            }
            set
            {
                this.Onesas_antal_forsoegChanging(value);
                this._esas_antal_forsoeg = value;
                this.Onesas_antal_forsoegChanged();
                this.OnPropertyChanged("esas_antal_forsoeg");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _esas_antal_forsoeg;
        partial void Onesas_antal_forsoegChanging(global::System.Nullable<int> value);
        partial void Onesas_antal_forsoegChanged();
        /// <summary>
        /// There are no comments for Property esas_aktivitet_type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> esas_aktivitet_type
        {
            get
            {
                return this._esas_aktivitet_type;
            }
            set
            {
                this.Onesas_aktivitet_typeChanging(value);
                this._esas_aktivitet_type = value;
                this.Onesas_aktivitet_typeChanged();
                this.OnPropertyChanged("esas_aktivitet_type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _esas_aktivitet_type;
        partial void Onesas_aktivitet_typeChanging(global::System.Nullable<int> value);
        partial void Onesas_aktivitet_typeChanged();
        /// <summary>
        /// There are no comments for Property esas_antal_merit_registreringer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> esas_antal_merit_registreringer
        {
            get
            {
                return this._esas_antal_merit_registreringer;
            }
            set
            {
                this.Onesas_antal_merit_registreringerChanging(value);
                this._esas_antal_merit_registreringer = value;
                this.Onesas_antal_merit_registreringerChanged();
                this.OnPropertyChanged("esas_antal_merit_registreringer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _esas_antal_merit_registreringer;
        partial void Onesas_antal_merit_registreringerChanging(global::System.Nullable<int> value);
        partial void Onesas_antal_merit_registreringerChanged();
        /// <summary>
        /// There are no comments for Property esas_bedoemmelsesresultat_7_trin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> esas_bedoemmelsesresultat_7_trin
        {
            get
            {
                return this._esas_bedoemmelsesresultat_7_trin;
            }
            set
            {
                this.Onesas_bedoemmelsesresultat_7_trinChanging(value);
                this._esas_bedoemmelsesresultat_7_trin = value;
                this.Onesas_bedoemmelsesresultat_7_trinChanged();
                this.OnPropertyChanged("esas_bedoemmelsesresultat_7_trin");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _esas_bedoemmelsesresultat_7_trin;
        partial void Onesas_bedoemmelsesresultat_7_trinChanging(global::System.Nullable<int> value);
        partial void Onesas_bedoemmelsesresultat_7_trinChanged();
        /// <summary>
        /// There are no comments for Property esas_bedoemmelsesresultat_bestaaet_ikke in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> esas_bedoemmelsesresultat_bestaaet_ikke
        {
            get
            {
                return this._esas_bedoemmelsesresultat_bestaaet_ikke;
            }
            set
            {
                this.Onesas_bedoemmelsesresultat_bestaaet_ikkeChanging(value);
                this._esas_bedoemmelsesresultat_bestaaet_ikke = value;
                this.Onesas_bedoemmelsesresultat_bestaaet_ikkeChanged();
                this.OnPropertyChanged("esas_bedoemmelsesresultat_bestaaet_ikke");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _esas_bedoemmelsesresultat_bestaaet_ikke;
        partial void Onesas_bedoemmelsesresultat_bestaaet_ikkeChanging(global::System.Nullable<int> value);
        partial void Onesas_bedoemmelsesresultat_bestaaet_ikkeChanged();
        /// <summary>
        /// There are no comments for Property esas_beregnet_bestaaet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<bool> esas_beregnet_bestaaet
        {
            get
            {
                return this._esas_beregnet_bestaaet;
            }
            set
            {
                this.Onesas_beregnet_bestaaetChanging(value);
                this._esas_beregnet_bestaaet = value;
                this.Onesas_beregnet_bestaaetChanged();
                this.OnPropertyChanged("esas_beregnet_bestaaet");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _esas_beregnet_bestaaet;
        partial void Onesas_beregnet_bestaaetChanging(global::System.Nullable<bool> value);
        partial void Onesas_beregnet_bestaaetChanged();
        /// <summary>
        /// There are no comments for Property esas_ects in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<decimal> esas_ects
        {
            get
            {
                return this._esas_ects;
            }
            set
            {
                this.Onesas_ectsChanging(value);
                this._esas_ects = value;
                this.Onesas_ectsChanged();
                this.OnPropertyChanged("esas_ects");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<decimal> _esas_ects;
        partial void Onesas_ectsChanging(global::System.Nullable<decimal> value);
        partial void Onesas_ectsChanged();
        /// <summary>
        /// There are no comments for Property esas_fejlbesked_fra_inrule in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_fejlbesked_fra_inrule
        {
            get
            {
                return this._esas_fejlbesked_fra_inrule;
            }
            set
            {
                this.Onesas_fejlbesked_fra_inruleChanging(value);
                this._esas_fejlbesked_fra_inrule = value;
                this.Onesas_fejlbesked_fra_inruleChanged();
                this.OnPropertyChanged("esas_fejlbesked_fra_inrule");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_fejlbesked_fra_inrule;
        partial void Onesas_fejlbesked_fra_inruleChanging(string value);
        partial void Onesas_fejlbesked_fra_inruleChanged();
        /// <summary>
        /// There are no comments for Property esas_navn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_navn
        {
            get
            {
                return this._esas_navn;
            }
            set
            {
                this.Onesas_navnChanging(value);
                this._esas_navn = value;
                this.Onesas_navnChanged();
                this.OnPropertyChanged("esas_navn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_navn;
        partial void Onesas_navnChanging(string value);
        partial void Onesas_navnChanged();
        /// <summary>
        /// There are no comments for Property esas_registreret_merit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<bool> esas_registreret_merit
        {
            get
            {
                return this._esas_registreret_merit;
            }
            set
            {
                this.Onesas_registreret_meritChanging(value);
                this._esas_registreret_merit = value;
                this.Onesas_registreret_meritChanged();
                this.OnPropertyChanged("esas_registreret_merit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _esas_registreret_merit;
        partial void Onesas_registreret_meritChanging(global::System.Nullable<bool> value);
        partial void Onesas_registreret_meritChanged();
        /// <summary>
        /// There are no comments for Property esas_semester_nummer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int esas_semester_nummer
        {
            get
            {
                return this._esas_semester_nummer;
            }
            set
            {
                this.Onesas_semester_nummerChanging(value);
                this._esas_semester_nummer = value;
                this.Onesas_semester_nummerChanged();
                this.OnPropertyChanged("esas_semester_nummer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _esas_semester_nummer;
        partial void Onesas_semester_nummerChanging(int value);
        partial void Onesas_semester_nummerChanged();
        /// <summary>
        /// There are no comments for Property esas_startdato in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> esas_startdato
        {
            get
            {
                return this._esas_startdato;
            }
            set
            {
                this.Onesas_startdatoChanging(value);
                this._esas_startdato = value;
                this.Onesas_startdatoChanged();
                this.OnPropertyChanged("esas_startdato");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _esas_startdato;
        partial void Onesas_startdatoChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void Onesas_startdatoChanged();
        /// <summary>
        /// There are no comments for Property esas_slutdato in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> esas_slutdato
        {
            get
            {
                return this._esas_slutdato;
            }
            set
            {
                this.Onesas_slutdatoChanging(value);
                this._esas_slutdato = value;
                this.Onesas_slutdatoChanged();
                this.OnPropertyChanged("esas_slutdato");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _esas_slutdato;
        partial void Onesas_slutdatoChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void Onesas_slutdatoChanged();
        /// <summary>
        /// There are no comments for Property esas_indskrivningsform_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_indskrivningsform_id
        {
            get
            {
                return this._esas_indskrivningsform_id;
            }
            set
            {
                this.Onesas_indskrivningsform_idChanging(value);
                this._esas_indskrivningsform_id = value;
                this.Onesas_indskrivningsform_idChanged();
                this.OnPropertyChanged("esas_indskrivningsform_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_indskrivningsform_id;
        partial void Onesas_indskrivningsform_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_indskrivningsform_idChanged();
        /// <summary>
        /// There are no comments for Property esas_uvm_fagkode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> esas_uvm_fagkode
        {
            get
            {
                return this._esas_uvm_fagkode;
            }
            set
            {
                this.Onesas_uvm_fagkodeChanging(value);
                this._esas_uvm_fagkode = value;
                this.Onesas_uvm_fagkodeChanged();
                this.OnPropertyChanged("esas_uvm_fagkode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _esas_uvm_fagkode;
        partial void Onesas_uvm_fagkodeChanging(global::System.Nullable<int> value);
        partial void Onesas_uvm_fagkodeChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _CreatedBy;
        partial void OnCreatedByChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property CreatedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> CreatedOn
        {
            get
            {
                return this._CreatedOn;
            }
            set
            {
                this.OnCreatedOnChanging(value);
                this._CreatedOn = value;
                this.OnCreatedOnChanged();
                this.OnPropertyChanged("CreatedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _CreatedOn;
        partial void OnCreatedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedOnChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _ModifiedBy;
        partial void OnModifiedByChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> ModifiedOn
        {
            get
            {
                return this._ModifiedOn;
            }
            set
            {
                this.OnModifiedOnChanging(value);
                this._ModifiedOn = value;
                this.OnModifiedOnChanged();
                this.OnPropertyChanged("ModifiedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _ModifiedOn;
        partial void OnModifiedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedOnChanged();
        /// <summary>
        /// There are no comments for Property OwningBusinessUnit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> OwningBusinessUnit
        {
            get
            {
                return this._OwningBusinessUnit;
            }
            set
            {
                this.OnOwningBusinessUnitChanging(value);
                this._OwningBusinessUnit = value;
                this.OnOwningBusinessUnitChanged();
                this.OnPropertyChanged("OwningBusinessUnit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _OwningBusinessUnit;
        partial void OnOwningBusinessUnitChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnOwningBusinessUnitChanged();
        /// <summary>
        /// There are no comments for Property statecode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> statecode
        {
            get
            {
                return this._statecode;
            }
            set
            {
                this.OnstatecodeChanging(value);
                this._statecode = value;
                this.OnstatecodeChanged();
                this.OnPropertyChanged("statecode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _statecode;
        partial void OnstatecodeChanging(global::System.Nullable<int> value);
        partial void OnstatecodeChanged();
        /// <summary>
        /// There are no comments for Property statuscode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> statuscode
        {
            get
            {
                return this._statuscode;
            }
            set
            {
                this.OnstatuscodeChanging(value);
                this._statuscode = value;
                this.OnstatuscodeChanged();
                this.OnPropertyChanged("statuscode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _statuscode;
        partial void OnstatuscodeChanging(global::System.Nullable<int> value);
        partial void OnstatuscodeChanged();
        /// <summary>
        /// There are no comments for Property esas_pue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.PlanlaegningsUddannelseselement esas_pue
        {
            get
            {
                return this._esas_pue;
            }
            set
            {
                this.Onesas_pueChanging(value);
                this._esas_pue = value;
                this.Onesas_pueChanged();
                this.OnPropertyChanged("esas_pue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.PlanlaegningsUddannelseselement _esas_pue;
        partial void Onesas_pueChanging(global::esas.Dynamics.Models.Contracts.PlanlaegningsUddannelseselement value);
        partial void Onesas_pueChanged();
        /// <summary>
        /// There are no comments for Property esas_uddannelseselement in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.StruktureltUddannelseselement esas_uddannelseselement
        {
            get
            {
                return this._esas_uddannelseselement;
            }
            set
            {
                this.Onesas_uddannelseselementChanging(value);
                this._esas_uddannelseselement = value;
                this.Onesas_uddannelseselementChanged();
                this.OnPropertyChanged("esas_uddannelseselement");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.StruktureltUddannelseselement _esas_uddannelseselement;
        partial void Onesas_uddannelseselementChanging(global::esas.Dynamics.Models.Contracts.StruktureltUddannelseselement value);
        partial void Onesas_uddannelseselementChanged();
        /// <summary>
        /// There are no comments for Property esas_studieforloeb in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.Studieforloeb esas_studieforloeb
        {
            get
            {
                return this._esas_studieforloeb;
            }
            set
            {
                this.Onesas_studieforloebChanging(value);
                this._esas_studieforloeb = value;
                this.Onesas_studieforloebChanged();
                this.OnPropertyChanged("esas_studieforloeb");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.Studieforloeb _esas_studieforloeb;
        partial void Onesas_studieforloebChanging(global::esas.Dynamics.Models.Contracts.Studieforloeb value);
        partial void Onesas_studieforloebChanged();
        /// <summary>
        /// There are no comments for Property esas_hold in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.Hold esas_hold
        {
            get
            {
                return this._esas_hold;
            }
            set
            {
                this.Onesas_holdChanging(value);
                this._esas_hold = value;
                this.Onesas_holdChanged();
                this.OnPropertyChanged("esas_hold");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.Hold _esas_hold;
        partial void Onesas_holdChanging(global::esas.Dynamics.Models.Contracts.Hold value);
        partial void Onesas_holdChanged();
        /// <summary>
        /// There are no comments for Property esas_bedoemmelsesresultat in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.Karakter esas_bedoemmelsesresultat
        {
            get
            {
                return this._esas_bedoemmelsesresultat;
            }
            set
            {
                this.Onesas_bedoemmelsesresultatChanging(value);
                this._esas_bedoemmelsesresultat = value;
                this.Onesas_bedoemmelsesresultatChanged();
                this.OnPropertyChanged("esas_bedoemmelsesresultat");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.Karakter _esas_bedoemmelsesresultat;
        partial void Onesas_bedoemmelsesresultatChanging(global::esas.Dynamics.Models.Contracts.Karakter value);
        partial void Onesas_bedoemmelsesresultatChanged();
        /// <summary>
        /// There are no comments for Property esas_aktivitetsafdeling in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.Afdeling esas_aktivitetsafdeling
        {
            get
            {
                return this._esas_aktivitetsafdeling;
            }
            set
            {
                this.Onesas_aktivitetsafdelingChanging(value);
                this._esas_aktivitetsafdeling = value;
                this.Onesas_aktivitetsafdelingChanged();
                this.OnPropertyChanged("esas_aktivitetsafdeling");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.Afdeling _esas_aktivitetsafdeling;
        partial void Onesas_aktivitetsafdelingChanging(global::esas.Dynamics.Models.Contracts.Afdeling value);
        partial void Onesas_aktivitetsafdelingChanged();
        /// <summary>
        /// There are no comments for Property esas_udbud_af_valgfag in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.StruktureltUddannelseselement esas_udbud_af_valgfag
        {
            get
            {
                return this._esas_udbud_af_valgfag;
            }
            set
            {
                this.Onesas_udbud_af_valgfagChanging(value);
                this._esas_udbud_af_valgfag = value;
                this.Onesas_udbud_af_valgfagChanged();
                this.OnPropertyChanged("esas_udbud_af_valgfag");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.StruktureltUddannelseselement _esas_udbud_af_valgfag;
        partial void Onesas_udbud_af_valgfagChanging(global::esas.Dynamics.Models.Contracts.StruktureltUddannelseselement value);
        partial void Onesas_udbud_af_valgfagChanged();
        /// <summary>
        /// There are no comments for Property list_esas_praktikophold in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Praktikophold> list_esas_praktikophold
        {
            get
            {
                return this._list_esas_praktikophold;
            }
            set
            {
                this.Onlist_esas_praktikopholdChanging(value);
                this._list_esas_praktikophold = value;
                this.Onlist_esas_praktikopholdChanged();
                this.OnPropertyChanged("list_esas_praktikophold");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Praktikophold> _list_esas_praktikophold = new global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Praktikophold>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void Onlist_esas_praktikopholdChanging(global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Praktikophold> value);
        partial void Onlist_esas_praktikopholdChanged();
        /// <summary>
        /// There are no comments for Property list_esas_bedoemmelse in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Bedoemmelse> list_esas_bedoemmelse
        {
            get
            {
                return this._list_esas_bedoemmelse;
            }
            set
            {
                this.Onlist_esas_bedoemmelseChanging(value);
                this._list_esas_bedoemmelse = value;
                this.Onlist_esas_bedoemmelseChanged();
                this.OnPropertyChanged("list_esas_bedoemmelse");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Bedoemmelse> _list_esas_bedoemmelse = new global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Bedoemmelse>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void Onlist_esas_bedoemmelseChanging(global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Bedoemmelse> value);
        partial void Onlist_esas_bedoemmelseChanged();
        /// <summary>
        /// There are no comments for Property list_esas_meritregistrering in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.MeritRegistrering> list_esas_meritregistrering
        {
            get
            {
                return this._list_esas_meritregistrering;
            }
            set
            {
                this.Onlist_esas_meritregistreringChanging(value);
                this._list_esas_meritregistrering = value;
                this.Onlist_esas_meritregistreringChanged();
                this.OnPropertyChanged("list_esas_meritregistrering");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.MeritRegistrering> _list_esas_meritregistrering = new global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.MeritRegistrering>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void Onlist_esas_meritregistreringChanging(global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.MeritRegistrering> value);
        partial void Onlist_esas_meritregistreringChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
