//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 03-03-2021 10:44:52
namespace esas.Dynamics.Models.Contracts
{
    /// <summary>
    /// There are no comments for HoldSingle in the schema.
    /// </summary>
    public partial class HoldSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Hold>
    {
        /// <summary>
        /// Initialize a new HoldSingle object.
        /// </summary>
        public HoldSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new HoldSingle object.
        /// </summary>
        public HoldSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new HoldSingle object.
        /// </summary>
        public HoldSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Hold> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for esas_planlaegningsuddannelseselement in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.PlanlaegningsUddannelseselementSingle esas_planlaegningsuddannelseselement
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._esas_planlaegningsuddannelseselement == null))
                {
                    this._esas_planlaegningsuddannelseselement = new global::esas.Dynamics.Models.Contracts.PlanlaegningsUddannelseselementSingle(this.Context, GetPath("esas_planlaegningsuddannelseselement"));
                }
                return this._esas_planlaegningsuddannelseselement;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.PlanlaegningsUddannelseselementSingle _esas_planlaegningsuddannelseselement;
        /// <summary>
        /// There are no comments for esas_institution in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.InstitutionVirksomhedSingle esas_institution
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._esas_institution == null))
                {
                    this._esas_institution = new global::esas.Dynamics.Models.Contracts.InstitutionVirksomhedSingle(this.Context, GetPath("esas_institution"));
                }
                return this._esas_institution;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.InstitutionVirksomhedSingle _esas_institution;
        /// <summary>
        /// There are no comments for esas_aktivitetsafdeling in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.AfdelingSingle esas_aktivitetsafdeling
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._esas_aktivitetsafdeling == null))
                {
                    this._esas_aktivitetsafdeling = new global::esas.Dynamics.Models.Contracts.AfdelingSingle(this.Context, GetPath("esas_aktivitetsafdeling"));
                }
                return this._esas_aktivitetsafdeling;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.AfdelingSingle _esas_aktivitetsafdeling;
        /// <summary>
        /// There are no comments for esas_publicering in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.PubliceringSingle esas_publicering
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._esas_publicering == null))
                {
                    this._esas_publicering = new global::esas.Dynamics.Models.Contracts.PubliceringSingle(this.Context, GetPath("esas_publicering"));
                }
                return this._esas_publicering;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.PubliceringSingle _esas_publicering;
        /// <summary>
        /// There are no comments for esas_aktivitetsudbud in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.AktivitetsudbudSingle esas_aktivitetsudbud
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._esas_aktivitetsudbud == null))
                {
                    this._esas_aktivitetsudbud = new global::esas.Dynamics.Models.Contracts.AktivitetsudbudSingle(this.Context, GetPath("esas_aktivitetsudbud"));
                }
                return this._esas_aktivitetsudbud;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.AktivitetsudbudSingle _esas_aktivitetsudbud;
        /// <summary>
        /// There are no comments for list_esas_fagpersonsrelation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.Fagpersonsrelation> list_esas_fagpersonsrelation
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._list_esas_fagpersonsrelation == null))
                {
                    this._list_esas_fagpersonsrelation = Context.CreateQuery<global::esas.Dynamics.Models.Contracts.Fagpersonsrelation>(GetPath("list_esas_fagpersonsrelation"));
                }
                return this._list_esas_fagpersonsrelation;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.Fagpersonsrelation> _list_esas_fagpersonsrelation;
        /// <summary>
        /// There are no comments for list_esas_uddannelseselement_gennemfoerelse in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.GennemfoerelsesUddannelseselement> list_esas_uddannelseselement_gennemfoerelse
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._list_esas_uddannelseselement_gennemfoerelse == null))
                {
                    this._list_esas_uddannelseselement_gennemfoerelse = Context.CreateQuery<global::esas.Dynamics.Models.Contracts.GennemfoerelsesUddannelseselement>(GetPath("list_esas_uddannelseselement_gennemfoerelse"));
                }
                return this._list_esas_uddannelseselement_gennemfoerelse;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.GennemfoerelsesUddannelseselement> _list_esas_uddannelseselement_gennemfoerelse;
        /// <summary>
        /// There are no comments for list_esas_studieforloeb in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.Studieforloeb> list_esas_studieforloeb
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._list_esas_studieforloeb == null))
                {
                    this._list_esas_studieforloeb = Context.CreateQuery<global::esas.Dynamics.Models.Contracts.Studieforloeb>(GetPath("list_esas_studieforloeb"));
                }
                return this._list_esas_studieforloeb;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.Studieforloeb> _list_esas_studieforloeb;
    }
    /// <summary>
    /// There are no comments for Hold in the schema.
    /// </summary>
    /// <KeyProperties>
    /// esas_holdId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("esas_holdId")]
    public partial class Hold : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property esas_holdId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_holdId
        {
            get
            {
                return this._esas_holdId;
            }
            set
            {
                this.Onesas_holdIdChanging(value);
                this._esas_holdId = value;
                this.Onesas_holdIdChanged();
                this.OnPropertyChanged("esas_holdId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_holdId;
        partial void Onesas_holdIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_holdIdChanged();
        /// <summary>
        /// There are no comments for Property esas_planlaegningsuddannelseselement_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_planlaegningsuddannelseselement_id
        {
            get
            {
                return this._esas_planlaegningsuddannelseselement_id;
            }
            set
            {
                this.Onesas_planlaegningsuddannelseselement_idChanging(value);
                this._esas_planlaegningsuddannelseselement_id = value;
                this.Onesas_planlaegningsuddannelseselement_idChanged();
                this.OnPropertyChanged("esas_planlaegningsuddannelseselement_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_planlaegningsuddannelseselement_id;
        partial void Onesas_planlaegningsuddannelseselement_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_planlaegningsuddannelseselement_idChanged();
        /// <summary>
        /// There are no comments for Property esas_institution_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_institution_id
        {
            get
            {
                return this._esas_institution_id;
            }
            set
            {
                this.Onesas_institution_idChanging(value);
                this._esas_institution_id = value;
                this.Onesas_institution_idChanged();
                this.OnPropertyChanged("esas_institution_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_institution_id;
        partial void Onesas_institution_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_institution_idChanged();
        /// <summary>
        /// There are no comments for Property esas_aktivitetsafdeling_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_aktivitetsafdeling_id
        {
            get
            {
                return this._esas_aktivitetsafdeling_id;
            }
            set
            {
                this.Onesas_aktivitetsafdeling_idChanging(value);
                this._esas_aktivitetsafdeling_id = value;
                this.Onesas_aktivitetsafdeling_idChanged();
                this.OnPropertyChanged("esas_aktivitetsafdeling_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_aktivitetsafdeling_id;
        partial void Onesas_aktivitetsafdeling_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_aktivitetsafdeling_idChanged();
        /// <summary>
        /// There are no comments for Property esas_publicering_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_publicering_id
        {
            get
            {
                return this._esas_publicering_id;
            }
            set
            {
                this.Onesas_publicering_idChanging(value);
                this._esas_publicering_id = value;
                this.Onesas_publicering_idChanged();
                this.OnPropertyChanged("esas_publicering_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_publicering_id;
        partial void Onesas_publicering_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_publicering_idChanged();
        /// <summary>
        /// There are no comments for Property esas_aktivitetsudbud_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_aktivitetsudbud_id
        {
            get
            {
                return this._esas_aktivitetsudbud_id;
            }
            set
            {
                this.Onesas_aktivitetsudbud_idChanging(value);
                this._esas_aktivitetsudbud_id = value;
                this.Onesas_aktivitetsudbud_idChanged();
                this.OnPropertyChanged("esas_aktivitetsudbud_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_aktivitetsudbud_id;
        partial void Onesas_aktivitetsudbud_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_aktivitetsudbud_idChanged();
        /// <summary>
        /// There are no comments for Property esas_antal_uddannelseselement_gennemfoerelse in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> esas_antal_uddannelseselement_gennemfoerelse
        {
            get
            {
                return this._esas_antal_uddannelseselement_gennemfoerelse;
            }
            set
            {
                this.Onesas_antal_uddannelseselement_gennemfoerelseChanging(value);
                this._esas_antal_uddannelseselement_gennemfoerelse = value;
                this.Onesas_antal_uddannelseselement_gennemfoerelseChanged();
                this.OnPropertyChanged("esas_antal_uddannelseselement_gennemfoerelse");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _esas_antal_uddannelseselement_gennemfoerelse;
        partial void Onesas_antal_uddannelseselement_gennemfoerelseChanging(global::System.Nullable<int> value);
        partial void Onesas_antal_uddannelseselement_gennemfoerelseChanged();
        /// <summary>
        /// There are no comments for Property esas_holdnummer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_holdnummer
        {
            get
            {
                return this._esas_holdnummer;
            }
            set
            {
                this.Onesas_holdnummerChanging(value);
                this._esas_holdnummer = value;
                this.Onesas_holdnummerChanged();
                this.OnPropertyChanged("esas_holdnummer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_holdnummer;
        partial void Onesas_holdnummerChanging(string value);
        partial void Onesas_holdnummerChanged();
        /// <summary>
        /// There are no comments for Property esas_holdrelation_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_holdrelation_id
        {
            get
            {
                return this._esas_holdrelation_id;
            }
            set
            {
                this.Onesas_holdrelation_idChanging(value);
                this._esas_holdrelation_id = value;
                this.Onesas_holdrelation_idChanged();
                this.OnPropertyChanged("esas_holdrelation_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_holdrelation_id;
        partial void Onesas_holdrelation_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_holdrelation_idChanged();
        /// <summary>
        /// There are no comments for Property esas_holdtype in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> esas_holdtype
        {
            get
            {
                return this._esas_holdtype;
            }
            set
            {
                this.Onesas_holdtypeChanging(value);
                this._esas_holdtype = value;
                this.Onesas_holdtypeChanged();
                this.OnPropertyChanged("esas_holdtype");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _esas_holdtype;
        partial void Onesas_holdtypeChanging(global::System.Nullable<int> value);
        partial void Onesas_holdtypeChanged();
        /// <summary>
        /// There are no comments for Property esas_loebenr in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_loebenr
        {
            get
            {
                return this._esas_loebenr;
            }
            set
            {
                this.Onesas_loebenrChanging(value);
                this._esas_loebenr = value;
                this.Onesas_loebenrChanged();
                this.OnPropertyChanged("esas_loebenr");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_loebenr;
        partial void Onesas_loebenrChanging(string value);
        partial void Onesas_loebenrChanged();
        /// <summary>
        /// There are no comments for Property esas_navn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_navn
        {
            get
            {
                return this._esas_navn;
            }
            set
            {
                this.Onesas_navnChanging(value);
                this._esas_navn = value;
                this.Onesas_navnChanged();
                this.OnPropertyChanged("esas_navn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_navn;
        partial void Onesas_navnChanging(string value);
        partial void Onesas_navnChanged();
        /// <summary>
        /// There are no comments for Property esas_navn_dansk in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_navn_dansk
        {
            get
            {
                return this._esas_navn_dansk;
            }
            set
            {
                this.Onesas_navn_danskChanging(value);
                this._esas_navn_dansk = value;
                this.Onesas_navn_danskChanged();
                this.OnPropertyChanged("esas_navn_dansk");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_navn_dansk;
        partial void Onesas_navn_danskChanging(string value);
        partial void Onesas_navn_danskChanged();
        /// <summary>
        /// There are no comments for Property esas_navn_engelsk in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_navn_engelsk
        {
            get
            {
                return this._esas_navn_engelsk;
            }
            set
            {
                this.Onesas_navn_engelskChanging(value);
                this._esas_navn_engelsk = value;
                this.Onesas_navn_engelskChanged();
                this.OnPropertyChanged("esas_navn_engelsk");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_navn_engelsk;
        partial void Onesas_navn_engelskChanging(string value);
        partial void Onesas_navn_engelskChanged();
        /// <summary>
        /// There are no comments for Property esas_startdato in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> esas_startdato
        {
            get
            {
                return this._esas_startdato;
            }
            set
            {
                this.Onesas_startdatoChanging(value);
                this._esas_startdato = value;
                this.Onesas_startdatoChanged();
                this.OnPropertyChanged("esas_startdato");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _esas_startdato;
        partial void Onesas_startdatoChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void Onesas_startdatoChanged();
        /// <summary>
        /// There are no comments for Property esas_slutdato in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> esas_slutdato
        {
            get
            {
                return this._esas_slutdato;
            }
            set
            {
                this.Onesas_slutdatoChanging(value);
                this._esas_slutdato = value;
                this.Onesas_slutdatoChanged();
                this.OnPropertyChanged("esas_slutdato");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _esas_slutdato;
        partial void Onesas_slutdatoChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void Onesas_slutdatoChanged();
        /// <summary>
        /// There are no comments for Property esas_fordelingsnoegle_prio_1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> esas_fordelingsnoegle_prio_1
        {
            get
            {
                return this._esas_fordelingsnoegle_prio_1;
            }
            set
            {
                this.Onesas_fordelingsnoegle_prio_1Changing(value);
                this._esas_fordelingsnoegle_prio_1 = value;
                this.Onesas_fordelingsnoegle_prio_1Changed();
                this.OnPropertyChanged("esas_fordelingsnoegle_prio_1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _esas_fordelingsnoegle_prio_1;
        partial void Onesas_fordelingsnoegle_prio_1Changing(global::System.Nullable<int> value);
        partial void Onesas_fordelingsnoegle_prio_1Changed();
        /// <summary>
        /// There are no comments for Property esas_fordelingsnoegle_prio_2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> esas_fordelingsnoegle_prio_2
        {
            get
            {
                return this._esas_fordelingsnoegle_prio_2;
            }
            set
            {
                this.Onesas_fordelingsnoegle_prio_2Changing(value);
                this._esas_fordelingsnoegle_prio_2 = value;
                this.Onesas_fordelingsnoegle_prio_2Changed();
                this.OnPropertyChanged("esas_fordelingsnoegle_prio_2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _esas_fordelingsnoegle_prio_2;
        partial void Onesas_fordelingsnoegle_prio_2Changing(global::System.Nullable<int> value);
        partial void Onesas_fordelingsnoegle_prio_2Changed();
        /// <summary>
        /// There are no comments for Property esas_fordelingsnoegle_max in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> esas_fordelingsnoegle_max
        {
            get
            {
                return this._esas_fordelingsnoegle_max;
            }
            set
            {
                this.Onesas_fordelingsnoegle_maxChanging(value);
                this._esas_fordelingsnoegle_max = value;
                this.Onesas_fordelingsnoegle_maxChanged();
                this.OnPropertyChanged("esas_fordelingsnoegle_max");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _esas_fordelingsnoegle_max;
        partial void Onesas_fordelingsnoegle_maxChanging(global::System.Nullable<int> value);
        partial void Onesas_fordelingsnoegle_maxChanged();
        /// <summary>
        /// There are no comments for Property esas_fordelingsnoegle_min in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> esas_fordelingsnoegle_min
        {
            get
            {
                return this._esas_fordelingsnoegle_min;
            }
            set
            {
                this.Onesas_fordelingsnoegle_minChanging(value);
                this._esas_fordelingsnoegle_min = value;
                this.Onesas_fordelingsnoegle_minChanged();
                this.OnPropertyChanged("esas_fordelingsnoegle_min");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _esas_fordelingsnoegle_min;
        partial void Onesas_fordelingsnoegle_minChanging(global::System.Nullable<int> value);
        partial void Onesas_fordelingsnoegle_minChanged();
        /// <summary>
        /// There are no comments for Property esas_fordeling_prio_1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<bool> esas_fordeling_prio_1
        {
            get
            {
                return this._esas_fordeling_prio_1;
            }
            set
            {
                this.Onesas_fordeling_prio_1Changing(value);
                this._esas_fordeling_prio_1 = value;
                this.Onesas_fordeling_prio_1Changed();
                this.OnPropertyChanged("esas_fordeling_prio_1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _esas_fordeling_prio_1;
        partial void Onesas_fordeling_prio_1Changing(global::System.Nullable<bool> value);
        partial void Onesas_fordeling_prio_1Changed();
        /// <summary>
        /// There are no comments for Property esas_fordeling_prio_2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<bool> esas_fordeling_prio_2
        {
            get
            {
                return this._esas_fordeling_prio_2;
            }
            set
            {
                this.Onesas_fordeling_prio_2Changing(value);
                this._esas_fordeling_prio_2 = value;
                this.Onesas_fordeling_prio_2Changed();
                this.OnPropertyChanged("esas_fordeling_prio_2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _esas_fordeling_prio_2;
        partial void Onesas_fordeling_prio_2Changing(global::System.Nullable<bool> value);
        partial void Onesas_fordeling_prio_2Changed();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _CreatedBy;
        partial void OnCreatedByChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property CreatedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> CreatedOn
        {
            get
            {
                return this._CreatedOn;
            }
            set
            {
                this.OnCreatedOnChanging(value);
                this._CreatedOn = value;
                this.OnCreatedOnChanged();
                this.OnPropertyChanged("CreatedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _CreatedOn;
        partial void OnCreatedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedOnChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _ModifiedBy;
        partial void OnModifiedByChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> ModifiedOn
        {
            get
            {
                return this._ModifiedOn;
            }
            set
            {
                this.OnModifiedOnChanging(value);
                this._ModifiedOn = value;
                this.OnModifiedOnChanged();
                this.OnPropertyChanged("ModifiedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _ModifiedOn;
        partial void OnModifiedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedOnChanged();
        /// <summary>
        /// There are no comments for Property OwningBusinessUnit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> OwningBusinessUnit
        {
            get
            {
                return this._OwningBusinessUnit;
            }
            set
            {
                this.OnOwningBusinessUnitChanging(value);
                this._OwningBusinessUnit = value;
                this.OnOwningBusinessUnitChanged();
                this.OnPropertyChanged("OwningBusinessUnit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _OwningBusinessUnit;
        partial void OnOwningBusinessUnitChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnOwningBusinessUnitChanged();
        /// <summary>
        /// There are no comments for Property statecode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> statecode
        {
            get
            {
                return this._statecode;
            }
            set
            {
                this.OnstatecodeChanging(value);
                this._statecode = value;
                this.OnstatecodeChanged();
                this.OnPropertyChanged("statecode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _statecode;
        partial void OnstatecodeChanging(global::System.Nullable<int> value);
        partial void OnstatecodeChanged();
        /// <summary>
        /// There are no comments for Property statuscode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> statuscode
        {
            get
            {
                return this._statuscode;
            }
            set
            {
                this.OnstatuscodeChanging(value);
                this._statuscode = value;
                this.OnstatuscodeChanged();
                this.OnPropertyChanged("statuscode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _statuscode;
        partial void OnstatuscodeChanging(global::System.Nullable<int> value);
        partial void OnstatuscodeChanged();
        /// <summary>
        /// There are no comments for Property esas_planlaegningsuddannelseselement in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.PlanlaegningsUddannelseselement esas_planlaegningsuddannelseselement
        {
            get
            {
                return this._esas_planlaegningsuddannelseselement;
            }
            set
            {
                this.Onesas_planlaegningsuddannelseselementChanging(value);
                this._esas_planlaegningsuddannelseselement = value;
                this.Onesas_planlaegningsuddannelseselementChanged();
                this.OnPropertyChanged("esas_planlaegningsuddannelseselement");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.PlanlaegningsUddannelseselement _esas_planlaegningsuddannelseselement;
        partial void Onesas_planlaegningsuddannelseselementChanging(global::esas.Dynamics.Models.Contracts.PlanlaegningsUddannelseselement value);
        partial void Onesas_planlaegningsuddannelseselementChanged();
        /// <summary>
        /// There are no comments for Property esas_institution in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.InstitutionVirksomhed esas_institution
        {
            get
            {
                return this._esas_institution;
            }
            set
            {
                this.Onesas_institutionChanging(value);
                this._esas_institution = value;
                this.Onesas_institutionChanged();
                this.OnPropertyChanged("esas_institution");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.InstitutionVirksomhed _esas_institution;
        partial void Onesas_institutionChanging(global::esas.Dynamics.Models.Contracts.InstitutionVirksomhed value);
        partial void Onesas_institutionChanged();
        /// <summary>
        /// There are no comments for Property esas_aktivitetsafdeling in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.Afdeling esas_aktivitetsafdeling
        {
            get
            {
                return this._esas_aktivitetsafdeling;
            }
            set
            {
                this.Onesas_aktivitetsafdelingChanging(value);
                this._esas_aktivitetsafdeling = value;
                this.Onesas_aktivitetsafdelingChanged();
                this.OnPropertyChanged("esas_aktivitetsafdeling");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.Afdeling _esas_aktivitetsafdeling;
        partial void Onesas_aktivitetsafdelingChanging(global::esas.Dynamics.Models.Contracts.Afdeling value);
        partial void Onesas_aktivitetsafdelingChanged();
        /// <summary>
        /// There are no comments for Property esas_publicering in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.Publicering esas_publicering
        {
            get
            {
                return this._esas_publicering;
            }
            set
            {
                this.Onesas_publiceringChanging(value);
                this._esas_publicering = value;
                this.Onesas_publiceringChanged();
                this.OnPropertyChanged("esas_publicering");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.Publicering _esas_publicering;
        partial void Onesas_publiceringChanging(global::esas.Dynamics.Models.Contracts.Publicering value);
        partial void Onesas_publiceringChanged();
        /// <summary>
        /// There are no comments for Property esas_aktivitetsudbud in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.Aktivitetsudbud esas_aktivitetsudbud
        {
            get
            {
                return this._esas_aktivitetsudbud;
            }
            set
            {
                this.Onesas_aktivitetsudbudChanging(value);
                this._esas_aktivitetsudbud = value;
                this.Onesas_aktivitetsudbudChanged();
                this.OnPropertyChanged("esas_aktivitetsudbud");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.Aktivitetsudbud _esas_aktivitetsudbud;
        partial void Onesas_aktivitetsudbudChanging(global::esas.Dynamics.Models.Contracts.Aktivitetsudbud value);
        partial void Onesas_aktivitetsudbudChanged();
        /// <summary>
        /// There are no comments for Property list_esas_fagpersonsrelation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Fagpersonsrelation> list_esas_fagpersonsrelation
        {
            get
            {
                return this._list_esas_fagpersonsrelation;
            }
            set
            {
                this.Onlist_esas_fagpersonsrelationChanging(value);
                this._list_esas_fagpersonsrelation = value;
                this.Onlist_esas_fagpersonsrelationChanged();
                this.OnPropertyChanged("list_esas_fagpersonsrelation");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Fagpersonsrelation> _list_esas_fagpersonsrelation = new global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Fagpersonsrelation>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void Onlist_esas_fagpersonsrelationChanging(global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Fagpersonsrelation> value);
        partial void Onlist_esas_fagpersonsrelationChanged();
        /// <summary>
        /// There are no comments for Property list_esas_uddannelseselement_gennemfoerelse in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.GennemfoerelsesUddannelseselement> list_esas_uddannelseselement_gennemfoerelse
        {
            get
            {
                return this._list_esas_uddannelseselement_gennemfoerelse;
            }
            set
            {
                this.Onlist_esas_uddannelseselement_gennemfoerelseChanging(value);
                this._list_esas_uddannelseselement_gennemfoerelse = value;
                this.Onlist_esas_uddannelseselement_gennemfoerelseChanged();
                this.OnPropertyChanged("list_esas_uddannelseselement_gennemfoerelse");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.GennemfoerelsesUddannelseselement> _list_esas_uddannelseselement_gennemfoerelse = new global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.GennemfoerelsesUddannelseselement>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void Onlist_esas_uddannelseselement_gennemfoerelseChanging(global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.GennemfoerelsesUddannelseselement> value);
        partial void Onlist_esas_uddannelseselement_gennemfoerelseChanged();
        /// <summary>
        /// There are no comments for Property list_esas_studieforloeb in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Studieforloeb> list_esas_studieforloeb
        {
            get
            {
                return this._list_esas_studieforloeb;
            }
            set
            {
                this.Onlist_esas_studieforloebChanging(value);
                this._list_esas_studieforloeb = value;
                this.Onlist_esas_studieforloebChanged();
                this.OnPropertyChanged("list_esas_studieforloeb");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Studieforloeb> _list_esas_studieforloeb = new global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Studieforloeb>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void Onlist_esas_studieforloebChanging(global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Studieforloeb> value);
        partial void Onlist_esas_studieforloebChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
