//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 03-03-2021 10:44:52
namespace esas.Dynamics.Models.Contracts
{
    /// <summary>
    /// There are no comments for InstitutionsoplysningerSingle in the schema.
    /// </summary>
    public partial class InstitutionsoplysningerSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Institutionsoplysninger>
    {
        /// <summary>
        /// Initialize a new InstitutionsoplysningerSingle object.
        /// </summary>
        public InstitutionsoplysningerSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new InstitutionsoplysningerSingle object.
        /// </summary>
        public InstitutionsoplysningerSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new InstitutionsoplysningerSingle object.
        /// </summary>
        public InstitutionsoplysningerSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Institutionsoplysninger> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for esas_institution_virksomhed in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.InstitutionVirksomhedSingle esas_institution_virksomhed
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._esas_institution_virksomhed == null))
                {
                    this._esas_institution_virksomhed = new global::esas.Dynamics.Models.Contracts.InstitutionVirksomhedSingle(this.Context, GetPath("esas_institution_virksomhed"));
                }
                return this._esas_institution_virksomhed;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.InstitutionVirksomhedSingle _esas_institution_virksomhed;
        /// <summary>
        /// There are no comments for list_esas_institution_virksomhed in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.InstitutionVirksomhed> list_esas_institution_virksomhed
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._list_esas_institution_virksomhed == null))
                {
                    this._list_esas_institution_virksomhed = Context.CreateQuery<global::esas.Dynamics.Models.Contracts.InstitutionVirksomhed>(GetPath("list_esas_institution_virksomhed"));
                }
                return this._list_esas_institution_virksomhed;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.InstitutionVirksomhed> _list_esas_institution_virksomhed;
    }
    /// <summary>
    /// There are no comments for Institutionsoplysninger in the schema.
    /// </summary>
    /// <KeyProperties>
    /// esas_institutionsoplysningerId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("esas_institutionsoplysningerId")]
    public partial class Institutionsoplysninger : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property esas_institutionsoplysningerId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_institutionsoplysningerId
        {
            get
            {
                return this._esas_institutionsoplysningerId;
            }
            set
            {
                this.Onesas_institutionsoplysningerIdChanging(value);
                this._esas_institutionsoplysningerId = value;
                this.Onesas_institutionsoplysningerIdChanged();
                this.OnPropertyChanged("esas_institutionsoplysningerId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_institutionsoplysningerId;
        partial void Onesas_institutionsoplysningerIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_institutionsoplysningerIdChanged();
        /// <summary>
        /// There are no comments for Property esas_institution_virksomhed_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_institution_virksomhed_id
        {
            get
            {
                return this._esas_institution_virksomhed_id;
            }
            set
            {
                this.Onesas_institution_virksomhed_idChanging(value);
                this._esas_institution_virksomhed_id = value;
                this.Onesas_institution_virksomhed_idChanged();
                this.OnPropertyChanged("esas_institution_virksomhed_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_institution_virksomhed_id;
        partial void Onesas_institution_virksomhed_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_institution_virksomhed_idChanged();
        /// <summary>
        /// There are no comments for Property esas_navn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_navn
        {
            get
            {
                return this._esas_navn;
            }
            set
            {
                this.Onesas_navnChanging(value);
                this._esas_navn = value;
                this.Onesas_navnChanged();
                this.OnPropertyChanged("esas_navn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_navn;
        partial void Onesas_navnChanging(string value);
        partial void Onesas_navnChanged();
        /// <summary>
        /// There are no comments for Property esas_markedsfoering in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<bool> esas_markedsfoering
        {
            get
            {
                return this._esas_markedsfoering;
            }
            set
            {
                this.Onesas_markedsfoeringChanging(value);
                this._esas_markedsfoering = value;
                this.Onesas_markedsfoeringChanged();
                this.OnPropertyChanged("esas_markedsfoering");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _esas_markedsfoering;
        partial void Onesas_markedsfoeringChanging(global::System.Nullable<bool> value);
        partial void Onesas_markedsfoeringChanged();
        /// <summary>
        /// There are no comments for Property esas_ns_debitor_nummer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_ns_debitor_nummer
        {
            get
            {
                return this._esas_ns_debitor_nummer;
            }
            set
            {
                this.Onesas_ns_debitor_nummerChanging(value);
                this._esas_ns_debitor_nummer = value;
                this.Onesas_ns_debitor_nummerChanged();
                this.OnPropertyChanged("esas_ns_debitor_nummer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_ns_debitor_nummer;
        partial void Onesas_ns_debitor_nummerChanging(string value);
        partial void Onesas_ns_debitor_nummerChanged();
        /// <summary>
        /// There are no comments for Property esas_samarbejdstype_rekvirent_privat in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<bool> esas_samarbejdstype_rekvirent_privat
        {
            get
            {
                return this._esas_samarbejdstype_rekvirent_privat;
            }
            set
            {
                this.Onesas_samarbejdstype_rekvirent_privatChanging(value);
                this._esas_samarbejdstype_rekvirent_privat = value;
                this.Onesas_samarbejdstype_rekvirent_privatChanged();
                this.OnPropertyChanged("esas_samarbejdstype_rekvirent_privat");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _esas_samarbejdstype_rekvirent_privat;
        partial void Onesas_samarbejdstype_rekvirent_privatChanging(global::System.Nullable<bool> value);
        partial void Onesas_samarbejdstype_rekvirent_privatChanged();
        /// <summary>
        /// There are no comments for Property esas_samarbejdstype_rekvirent_offentlig in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<bool> esas_samarbejdstype_rekvirent_offentlig
        {
            get
            {
                return this._esas_samarbejdstype_rekvirent_offentlig;
            }
            set
            {
                this.Onesas_samarbejdstype_rekvirent_offentligChanging(value);
                this._esas_samarbejdstype_rekvirent_offentlig = value;
                this.Onesas_samarbejdstype_rekvirent_offentligChanged();
                this.OnPropertyChanged("esas_samarbejdstype_rekvirent_offentlig");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _esas_samarbejdstype_rekvirent_offentlig;
        partial void Onesas_samarbejdstype_rekvirent_offentligChanging(global::System.Nullable<bool> value);
        partial void Onesas_samarbejdstype_rekvirent_offentligChanged();
        /// <summary>
        /// There are no comments for Property esas_samarbejdstype_praktiksted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<bool> esas_samarbejdstype_praktiksted
        {
            get
            {
                return this._esas_samarbejdstype_praktiksted;
            }
            set
            {
                this.Onesas_samarbejdstype_praktikstedChanging(value);
                this._esas_samarbejdstype_praktiksted = value;
                this.Onesas_samarbejdstype_praktikstedChanged();
                this.OnPropertyChanged("esas_samarbejdstype_praktiksted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _esas_samarbejdstype_praktiksted;
        partial void Onesas_samarbejdstype_praktikstedChanging(global::System.Nullable<bool> value);
        partial void Onesas_samarbejdstype_praktikstedChanged();
        /// <summary>
        /// There are no comments for Property esas_samarbejdstype_virksomhed in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<bool> esas_samarbejdstype_virksomhed
        {
            get
            {
                return this._esas_samarbejdstype_virksomhed;
            }
            set
            {
                this.Onesas_samarbejdstype_virksomhedChanging(value);
                this._esas_samarbejdstype_virksomhed = value;
                this.Onesas_samarbejdstype_virksomhedChanged();
                this.OnPropertyChanged("esas_samarbejdstype_virksomhed");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _esas_samarbejdstype_virksomhed;
        partial void Onesas_samarbejdstype_virksomhedChanging(global::System.Nullable<bool> value);
        partial void Onesas_samarbejdstype_virksomhedChanged();
        /// <summary>
        /// There are no comments for Property esas_samarbejdstype_uddannelsesinstitution in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<bool> esas_samarbejdstype_uddannelsesinstitution
        {
            get
            {
                return this._esas_samarbejdstype_uddannelsesinstitution;
            }
            set
            {
                this.Onesas_samarbejdstype_uddannelsesinstitutionChanging(value);
                this._esas_samarbejdstype_uddannelsesinstitution = value;
                this.Onesas_samarbejdstype_uddannelsesinstitutionChanged();
                this.OnPropertyChanged("esas_samarbejdstype_uddannelsesinstitution");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _esas_samarbejdstype_uddannelsesinstitution;
        partial void Onesas_samarbejdstype_uddannelsesinstitutionChanging(global::System.Nullable<bool> value);
        partial void Onesas_samarbejdstype_uddannelsesinstitutionChanged();
        /// <summary>
        /// There are no comments for Property esas_samarbejdstype_offentlig_institution in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<bool> esas_samarbejdstype_offentlig_institution
        {
            get
            {
                return this._esas_samarbejdstype_offentlig_institution;
            }
            set
            {
                this.Onesas_samarbejdstype_offentlig_institutionChanging(value);
                this._esas_samarbejdstype_offentlig_institution = value;
                this.Onesas_samarbejdstype_offentlig_institutionChanged();
                this.OnPropertyChanged("esas_samarbejdstype_offentlig_institution");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _esas_samarbejdstype_offentlig_institution;
        partial void Onesas_samarbejdstype_offentlig_institutionChanging(global::System.Nullable<bool> value);
        partial void Onesas_samarbejdstype_offentlig_institutionChanged();
        /// <summary>
        /// There are no comments for Property esas_dokumentafsendelsesmetode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> esas_dokumentafsendelsesmetode
        {
            get
            {
                return this._esas_dokumentafsendelsesmetode;
            }
            set
            {
                this.Onesas_dokumentafsendelsesmetodeChanging(value);
                this._esas_dokumentafsendelsesmetode = value;
                this.Onesas_dokumentafsendelsesmetodeChanged();
                this.OnPropertyChanged("esas_dokumentafsendelsesmetode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _esas_dokumentafsendelsesmetode;
        partial void Onesas_dokumentafsendelsesmetodeChanging(global::System.Nullable<int> value);
        partial void Onesas_dokumentafsendelsesmetodeChanged();
        /// <summary>
        /// There are no comments for Property esas_sidst_faktureret in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> esas_sidst_faktureret
        {
            get
            {
                return this._esas_sidst_faktureret;
            }
            set
            {
                this.Onesas_sidst_faktureretChanging(value);
                this._esas_sidst_faktureret = value;
                this.Onesas_sidst_faktureretChanged();
                this.OnPropertyChanged("esas_sidst_faktureret");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _esas_sidst_faktureret;
        partial void Onesas_sidst_faktureretChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void Onesas_sidst_faktureretChanged();
        /// <summary>
        /// There are no comments for Property esas_virksomhedsemail in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_virksomhedsemail
        {
            get
            {
                return this._esas_virksomhedsemail;
            }
            set
            {
                this.Onesas_virksomhedsemailChanging(value);
                this._esas_virksomhedsemail = value;
                this.Onesas_virksomhedsemailChanged();
                this.OnPropertyChanged("esas_virksomhedsemail");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_virksomhedsemail;
        partial void Onesas_virksomhedsemailChanging(string value);
        partial void Onesas_virksomhedsemailChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _CreatedBy;
        partial void OnCreatedByChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property CreatedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> CreatedOn
        {
            get
            {
                return this._CreatedOn;
            }
            set
            {
                this.OnCreatedOnChanging(value);
                this._CreatedOn = value;
                this.OnCreatedOnChanged();
                this.OnPropertyChanged("CreatedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _CreatedOn;
        partial void OnCreatedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedOnChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _ModifiedBy;
        partial void OnModifiedByChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> ModifiedOn
        {
            get
            {
                return this._ModifiedOn;
            }
            set
            {
                this.OnModifiedOnChanging(value);
                this._ModifiedOn = value;
                this.OnModifiedOnChanged();
                this.OnPropertyChanged("ModifiedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _ModifiedOn;
        partial void OnModifiedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedOnChanged();
        /// <summary>
        /// There are no comments for Property OwningBusinessUnit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> OwningBusinessUnit
        {
            get
            {
                return this._OwningBusinessUnit;
            }
            set
            {
                this.OnOwningBusinessUnitChanging(value);
                this._OwningBusinessUnit = value;
                this.OnOwningBusinessUnitChanged();
                this.OnPropertyChanged("OwningBusinessUnit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _OwningBusinessUnit;
        partial void OnOwningBusinessUnitChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnOwningBusinessUnitChanged();
        /// <summary>
        /// There are no comments for Property statecode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> statecode
        {
            get
            {
                return this._statecode;
            }
            set
            {
                this.OnstatecodeChanging(value);
                this._statecode = value;
                this.OnstatecodeChanged();
                this.OnPropertyChanged("statecode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _statecode;
        partial void OnstatecodeChanging(global::System.Nullable<int> value);
        partial void OnstatecodeChanged();
        /// <summary>
        /// There are no comments for Property statuscode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> statuscode
        {
            get
            {
                return this._statuscode;
            }
            set
            {
                this.OnstatuscodeChanging(value);
                this._statuscode = value;
                this.OnstatuscodeChanged();
                this.OnPropertyChanged("statuscode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _statuscode;
        partial void OnstatuscodeChanging(global::System.Nullable<int> value);
        partial void OnstatuscodeChanged();
        /// <summary>
        /// There are no comments for Property esas_institution_virksomhed in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.InstitutionVirksomhed esas_institution_virksomhed
        {
            get
            {
                return this._esas_institution_virksomhed;
            }
            set
            {
                this.Onesas_institution_virksomhedChanging(value);
                this._esas_institution_virksomhed = value;
                this.Onesas_institution_virksomhedChanged();
                this.OnPropertyChanged("esas_institution_virksomhed");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.InstitutionVirksomhed _esas_institution_virksomhed;
        partial void Onesas_institution_virksomhedChanging(global::esas.Dynamics.Models.Contracts.InstitutionVirksomhed value);
        partial void Onesas_institution_virksomhedChanged();
        /// <summary>
        /// There are no comments for Property list_esas_institution_virksomhed in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.InstitutionVirksomhed> list_esas_institution_virksomhed
        {
            get
            {
                return this._list_esas_institution_virksomhed;
            }
            set
            {
                this.Onlist_esas_institution_virksomhedChanging(value);
                this._list_esas_institution_virksomhed = value;
                this.Onlist_esas_institution_virksomhedChanged();
                this.OnPropertyChanged("list_esas_institution_virksomhed");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.InstitutionVirksomhed> _list_esas_institution_virksomhed = new global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.InstitutionVirksomhed>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void Onlist_esas_institution_virksomhedChanging(global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.InstitutionVirksomhed> value);
        partial void Onlist_esas_institution_virksomhedChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
