//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 03-03-2021 10:44:52
namespace esas.Dynamics.Models.Contracts
{
    /// <summary>
    /// There are no comments for KOTGruppeSingle in the schema.
    /// </summary>
    public partial class KOTGruppeSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<KOTGruppe>
    {
        /// <summary>
        /// Initialize a new KOTGruppeSingle object.
        /// </summary>
        public KOTGruppeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new KOTGruppeSingle object.
        /// </summary>
        public KOTGruppeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new KOTGruppeSingle object.
        /// </summary>
        public KOTGruppeSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<KOTGruppe> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for esas_omraadenummeropsaetning in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.OmraadenummeropsaetningSingle esas_omraadenummeropsaetning
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._esas_omraadenummeropsaetning == null))
                {
                    this._esas_omraadenummeropsaetning = new global::esas.Dynamics.Models.Contracts.OmraadenummeropsaetningSingle(this.Context, GetPath("esas_omraadenummeropsaetning"));
                }
                return this._esas_omraadenummeropsaetning;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.OmraadenummeropsaetningSingle _esas_omraadenummeropsaetning;
    }
    /// <summary>
    /// There are no comments for KOTGruppe in the schema.
    /// </summary>
    /// <KeyProperties>
    /// esas_kot_gruppeid
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("esas_kot_gruppeid")]
    public partial class KOTGruppe : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new KOTGruppe object.
        /// </summary>
        /// <param name="esas_automatisk_tildeling">Initial value of esas_automatisk_tildeling.</param>
        /// <param name="esas_periode_slut">Initial value of esas_periode_slut.</param>
        /// <param name="esas_periode_start">Initial value of esas_periode_start.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static KOTGruppe CreateKOTGruppe(bool esas_automatisk_tildeling, global::System.DateTimeOffset esas_periode_slut, global::System.DateTimeOffset esas_periode_start)
        {
            KOTGruppe kOTGruppe = new KOTGruppe();
            kOTGruppe.esas_automatisk_tildeling = esas_automatisk_tildeling;
            kOTGruppe.esas_periode_slut = esas_periode_slut;
            kOTGruppe.esas_periode_start = esas_periode_start;
            return kOTGruppe;
        }
        /// <summary>
        /// There are no comments for Property esas_kot_gruppeid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_kot_gruppeid
        {
            get
            {
                return this._esas_kot_gruppeid;
            }
            set
            {
                this.Onesas_kot_gruppeidChanging(value);
                this._esas_kot_gruppeid = value;
                this.Onesas_kot_gruppeidChanged();
                this.OnPropertyChanged("esas_kot_gruppeid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_kot_gruppeid;
        partial void Onesas_kot_gruppeidChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_kot_gruppeidChanged();
        /// <summary>
        /// There are no comments for Property esas_omraadenummeropsaetning_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_omraadenummeropsaetning_id
        {
            get
            {
                return this._esas_omraadenummeropsaetning_id;
            }
            set
            {
                this.Onesas_omraadenummeropsaetning_idChanging(value);
                this._esas_omraadenummeropsaetning_id = value;
                this.Onesas_omraadenummeropsaetning_idChanged();
                this.OnPropertyChanged("esas_omraadenummeropsaetning_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_omraadenummeropsaetning_id;
        partial void Onesas_omraadenummeropsaetning_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_omraadenummeropsaetning_idChanged();
        /// <summary>
        /// There are no comments for Property esas_automatisk_tildeling in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual bool esas_automatisk_tildeling
        {
            get
            {
                return this._esas_automatisk_tildeling;
            }
            set
            {
                this.Onesas_automatisk_tildelingChanging(value);
                this._esas_automatisk_tildeling = value;
                this.Onesas_automatisk_tildelingChanged();
                this.OnPropertyChanged("esas_automatisk_tildeling");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private bool _esas_automatisk_tildeling;
        partial void Onesas_automatisk_tildelingChanging(bool value);
        partial void Onesas_automatisk_tildelingChanged();
        /// <summary>
        /// There are no comments for Property esas_betegnelse in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_betegnelse
        {
            get
            {
                return this._esas_betegnelse;
            }
            set
            {
                this.Onesas_betegnelseChanging(value);
                this._esas_betegnelse = value;
                this.Onesas_betegnelseChanged();
                this.OnPropertyChanged("esas_betegnelse");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_betegnelse;
        partial void Onesas_betegnelseChanging(string value);
        partial void Onesas_betegnelseChanged();
        /// <summary>
        /// There are no comments for Property esas_gruppenummer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> esas_gruppenummer
        {
            get
            {
                return this._esas_gruppenummer;
            }
            set
            {
                this.Onesas_gruppenummerChanging(value);
                this._esas_gruppenummer = value;
                this.Onesas_gruppenummerChanged();
                this.OnPropertyChanged("esas_gruppenummer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _esas_gruppenummer;
        partial void Onesas_gruppenummerChanging(global::System.Nullable<int> value);
        partial void Onesas_gruppenummerChanged();
        /// <summary>
        /// There are no comments for Property esas_navn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_navn
        {
            get
            {
                return this._esas_navn;
            }
            set
            {
                this.Onesas_navnChanging(value);
                this._esas_navn = value;
                this.Onesas_navnChanged();
                this.OnPropertyChanged("esas_navn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_navn;
        partial void Onesas_navnChanging(string value);
        partial void Onesas_navnChanged();
        /// <summary>
        /// There are no comments for Property esas_periode_slut in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.DateTimeOffset esas_periode_slut
        {
            get
            {
                return this._esas_periode_slut;
            }
            set
            {
                this.Onesas_periode_slutChanging(value);
                this._esas_periode_slut = value;
                this.Onesas_periode_slutChanged();
                this.OnPropertyChanged("esas_periode_slut");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _esas_periode_slut;
        partial void Onesas_periode_slutChanging(global::System.DateTimeOffset value);
        partial void Onesas_periode_slutChanged();
        /// <summary>
        /// There are no comments for Property esas_periode_start in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.DateTimeOffset esas_periode_start
        {
            get
            {
                return this._esas_periode_start;
            }
            set
            {
                this.Onesas_periode_startChanging(value);
                this._esas_periode_start = value;
                this.Onesas_periode_startChanged();
                this.OnPropertyChanged("esas_periode_start");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _esas_periode_start;
        partial void Onesas_periode_startChanging(global::System.DateTimeOffset value);
        partial void Onesas_periode_startChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _CreatedBy;
        partial void OnCreatedByChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property CreatedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> CreatedOn
        {
            get
            {
                return this._CreatedOn;
            }
            set
            {
                this.OnCreatedOnChanging(value);
                this._CreatedOn = value;
                this.OnCreatedOnChanged();
                this.OnPropertyChanged("CreatedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _CreatedOn;
        partial void OnCreatedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedOnChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _ModifiedBy;
        partial void OnModifiedByChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> ModifiedOn
        {
            get
            {
                return this._ModifiedOn;
            }
            set
            {
                this.OnModifiedOnChanging(value);
                this._ModifiedOn = value;
                this.OnModifiedOnChanged();
                this.OnPropertyChanged("ModifiedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _ModifiedOn;
        partial void OnModifiedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedOnChanged();
        /// <summary>
        /// There are no comments for Property OwningBusinessUnit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> OwningBusinessUnit
        {
            get
            {
                return this._OwningBusinessUnit;
            }
            set
            {
                this.OnOwningBusinessUnitChanging(value);
                this._OwningBusinessUnit = value;
                this.OnOwningBusinessUnitChanged();
                this.OnPropertyChanged("OwningBusinessUnit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _OwningBusinessUnit;
        partial void OnOwningBusinessUnitChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnOwningBusinessUnitChanged();
        /// <summary>
        /// There are no comments for Property statecode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> statecode
        {
            get
            {
                return this._statecode;
            }
            set
            {
                this.OnstatecodeChanging(value);
                this._statecode = value;
                this.OnstatecodeChanged();
                this.OnPropertyChanged("statecode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _statecode;
        partial void OnstatecodeChanging(global::System.Nullable<int> value);
        partial void OnstatecodeChanged();
        /// <summary>
        /// There are no comments for Property statuscode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> statuscode
        {
            get
            {
                return this._statuscode;
            }
            set
            {
                this.OnstatuscodeChanging(value);
                this._statuscode = value;
                this.OnstatuscodeChanged();
                this.OnPropertyChanged("statuscode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _statuscode;
        partial void OnstatuscodeChanging(global::System.Nullable<int> value);
        partial void OnstatuscodeChanged();
        /// <summary>
        /// There are no comments for Property esas_omraadenummeropsaetning in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.Omraadenummeropsaetning esas_omraadenummeropsaetning
        {
            get
            {
                return this._esas_omraadenummeropsaetning;
            }
            set
            {
                this.Onesas_omraadenummeropsaetningChanging(value);
                this._esas_omraadenummeropsaetning = value;
                this.Onesas_omraadenummeropsaetningChanged();
                this.OnPropertyChanged("esas_omraadenummeropsaetning");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.Omraadenummeropsaetning _esas_omraadenummeropsaetning;
        partial void Onesas_omraadenummeropsaetningChanging(global::esas.Dynamics.Models.Contracts.Omraadenummeropsaetning value);
        partial void Onesas_omraadenummeropsaetningChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
