//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 03-03-2021 10:44:52
namespace esas.Dynamics.Models.Contracts
{
    /// <summary>
    /// There are no comments for OmraadenummeropsaetningSingle in the schema.
    /// </summary>
    public partial class OmraadenummeropsaetningSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Omraadenummeropsaetning>
    {
        /// <summary>
        /// Initialize a new OmraadenummeropsaetningSingle object.
        /// </summary>
        public OmraadenummeropsaetningSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new OmraadenummeropsaetningSingle object.
        /// </summary>
        public OmraadenummeropsaetningSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new OmraadenummeropsaetningSingle object.
        /// </summary>
        public OmraadenummeropsaetningSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Omraadenummeropsaetning> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for esas_ansoegningsopsaetning in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.AnsoegningsopsaetningSingle esas_ansoegningsopsaetning
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._esas_ansoegningsopsaetning == null))
                {
                    this._esas_ansoegningsopsaetning = new global::esas.Dynamics.Models.Contracts.AnsoegningsopsaetningSingle(this.Context, GetPath("esas_ansoegningsopsaetning"));
                }
                return this._esas_ansoegningsopsaetning;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.AnsoegningsopsaetningSingle _esas_ansoegningsopsaetning;
        /// <summary>
        /// There are no comments for esas_aktivitetsudbud in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.AktivitetsudbudSingle esas_aktivitetsudbud
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._esas_aktivitetsudbud == null))
                {
                    this._esas_aktivitetsudbud = new global::esas.Dynamics.Models.Contracts.AktivitetsudbudSingle(this.Context, GetPath("esas_aktivitetsudbud"));
                }
                return this._esas_aktivitetsudbud;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.AktivitetsudbudSingle _esas_aktivitetsudbud;
        /// <summary>
        /// There are no comments for esas_publicering in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.PubliceringSingle esas_publicering
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._esas_publicering == null))
                {
                    this._esas_publicering = new global::esas.Dynamics.Models.Contracts.PubliceringSingle(this.Context, GetPath("esas_publicering"));
                }
                return this._esas_publicering;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.PubliceringSingle _esas_publicering;
        /// <summary>
        /// There are no comments for esas_adgangskrav in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.AdgangskravSingle esas_adgangskrav
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._esas_adgangskrav == null))
                {
                    this._esas_adgangskrav = new global::esas.Dynamics.Models.Contracts.AdgangskravSingle(this.Context, GetPath("esas_adgangskrav"));
                }
                return this._esas_adgangskrav;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.AdgangskravSingle _esas_adgangskrav;
        /// <summary>
        /// There are no comments for list_esas_ansoegning in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.Ansoegning> list_esas_ansoegning
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._list_esas_ansoegning == null))
                {
                    this._list_esas_ansoegning = Context.CreateQuery<global::esas.Dynamics.Models.Contracts.Ansoegning>(GetPath("list_esas_ansoegning"));
                }
                return this._list_esas_ansoegning;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.Ansoegning> _list_esas_ansoegning;
        /// <summary>
        /// There are no comments for list_esas_gymnasielle_fagkrav in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.GymnasielleFagkrav> list_esas_gymnasielle_fagkrav
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._list_esas_gymnasielle_fagkrav == null))
                {
                    this._list_esas_gymnasielle_fagkrav = Context.CreateQuery<global::esas.Dynamics.Models.Contracts.GymnasielleFagkrav>(GetPath("list_esas_gymnasielle_fagkrav"));
                }
                return this._list_esas_gymnasielle_fagkrav;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.GymnasielleFagkrav> _list_esas_gymnasielle_fagkrav;
        /// <summary>
        /// There are no comments for list_esas_gymnasielle_karakterkrav in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.GymnasielleKarakterkrav> list_esas_gymnasielle_karakterkrav
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._list_esas_gymnasielle_karakterkrav == null))
                {
                    this._list_esas_gymnasielle_karakterkrav = Context.CreateQuery<global::esas.Dynamics.Models.Contracts.GymnasielleKarakterkrav>(GetPath("list_esas_gymnasielle_karakterkrav"));
                }
                return this._list_esas_gymnasielle_karakterkrav;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.GymnasielleKarakterkrav> _list_esas_gymnasielle_karakterkrav;
        /// <summary>
        /// There are no comments for list_esas_kot_gruppe in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.KOTGruppe> list_esas_kot_gruppe
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._list_esas_kot_gruppe == null))
                {
                    this._list_esas_kot_gruppe = Context.CreateQuery<global::esas.Dynamics.Models.Contracts.KOTGruppe>(GetPath("list_esas_kot_gruppe"));
                }
                return this._list_esas_kot_gruppe;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.KOTGruppe> _list_esas_kot_gruppe;
        /// <summary>
        /// There are no comments for list_esas_omraadespecialisering in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.Omraadespecialisering> list_esas_omraadespecialisering
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._list_esas_omraadespecialisering == null))
                {
                    this._list_esas_omraadespecialisering = Context.CreateQuery<global::esas.Dynamics.Models.Contracts.Omraadespecialisering>(GetPath("list_esas_omraadespecialisering"));
                }
                return this._list_esas_omraadespecialisering;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.Omraadespecialisering> _list_esas_omraadespecialisering;
        /// <summary>
        /// There are no comments for list_esas_kvalifikationskriterie in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.Kvalifikationskriterie> list_esas_kvalifikationskriterie
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._list_esas_kvalifikationskriterie == null))
                {
                    this._list_esas_kvalifikationskriterie = Context.CreateQuery<global::esas.Dynamics.Models.Contracts.Kvalifikationskriterie>(GetPath("list_esas_kvalifikationskriterie"));
                }
                return this._list_esas_kvalifikationskriterie;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::esas.Dynamics.Models.Contracts.Kvalifikationskriterie> _list_esas_kvalifikationskriterie;
    }
    /// <summary>
    /// There are no comments for Omraadenummeropsaetning in the schema.
    /// </summary>
    /// <KeyProperties>
    /// esas_omraadeopsaetningid
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("esas_omraadeopsaetningid")]
    public partial class Omraadenummeropsaetning : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property esas_omraadeopsaetningid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_omraadeopsaetningid
        {
            get
            {
                return this._esas_omraadeopsaetningid;
            }
            set
            {
                this.Onesas_omraadeopsaetningidChanging(value);
                this._esas_omraadeopsaetningid = value;
                this.Onesas_omraadeopsaetningidChanged();
                this.OnPropertyChanged("esas_omraadeopsaetningid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_omraadeopsaetningid;
        partial void Onesas_omraadeopsaetningidChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_omraadeopsaetningidChanged();
        /// <summary>
        /// There are no comments for Property esas_ansoegningsopsaetning_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_ansoegningsopsaetning_id
        {
            get
            {
                return this._esas_ansoegningsopsaetning_id;
            }
            set
            {
                this.Onesas_ansoegningsopsaetning_idChanging(value);
                this._esas_ansoegningsopsaetning_id = value;
                this.Onesas_ansoegningsopsaetning_idChanged();
                this.OnPropertyChanged("esas_ansoegningsopsaetning_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_ansoegningsopsaetning_id;
        partial void Onesas_ansoegningsopsaetning_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_ansoegningsopsaetning_idChanged();
        /// <summary>
        /// There are no comments for Property esas_aktivitetsudbud_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_aktivitetsudbud_id
        {
            get
            {
                return this._esas_aktivitetsudbud_id;
            }
            set
            {
                this.Onesas_aktivitetsudbud_idChanging(value);
                this._esas_aktivitetsudbud_id = value;
                this.Onesas_aktivitetsudbud_idChanged();
                this.OnPropertyChanged("esas_aktivitetsudbud_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_aktivitetsudbud_id;
        partial void Onesas_aktivitetsudbud_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_aktivitetsudbud_idChanged();
        /// <summary>
        /// There are no comments for Property esas_publicering_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_publicering_id
        {
            get
            {
                return this._esas_publicering_id;
            }
            set
            {
                this.Onesas_publicering_idChanging(value);
                this._esas_publicering_id = value;
                this.Onesas_publicering_idChanged();
                this.OnPropertyChanged("esas_publicering_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_publicering_id;
        partial void Onesas_publicering_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_publicering_idChanged();
        /// <summary>
        /// There are no comments for Property esas_adgangskrav_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_adgangskrav_id
        {
            get
            {
                return this._esas_adgangskrav_id;
            }
            set
            {
                this.Onesas_adgangskrav_idChanging(value);
                this._esas_adgangskrav_id = value;
                this.Onesas_adgangskrav_idChanged();
                this.OnPropertyChanged("esas_adgangskrav_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_adgangskrav_id;
        partial void Onesas_adgangskrav_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_adgangskrav_idChanged();
        /// <summary>
        /// There are no comments for Property esas_dimensionering_sommer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> esas_dimensionering_sommer
        {
            get
            {
                return this._esas_dimensionering_sommer;
            }
            set
            {
                this.Onesas_dimensionering_sommerChanging(value);
                this._esas_dimensionering_sommer = value;
                this.Onesas_dimensionering_sommerChanged();
                this.OnPropertyChanged("esas_dimensionering_sommer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _esas_dimensionering_sommer;
        partial void Onesas_dimensionering_sommerChanging(global::System.Nullable<int> value);
        partial void Onesas_dimensionering_sommerChanged();
        /// <summary>
        /// There are no comments for Property esas_dimensionering_vinter in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> esas_dimensionering_vinter
        {
            get
            {
                return this._esas_dimensionering_vinter;
            }
            set
            {
                this.Onesas_dimensionering_vinterChanging(value);
                this._esas_dimensionering_vinter = value;
                this.Onesas_dimensionering_vinterChanged();
                this.OnPropertyChanged("esas_dimensionering_vinter");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _esas_dimensionering_vinter;
        partial void Onesas_dimensionering_vinterChanging(global::System.Nullable<int> value);
        partial void Onesas_dimensionering_vinterChanged();
        /// <summary>
        /// There are no comments for Property esas_omraadespecialiseringsprioriteter_max in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> esas_omraadespecialiseringsprioriteter_max
        {
            get
            {
                return this._esas_omraadespecialiseringsprioriteter_max;
            }
            set
            {
                this.Onesas_omraadespecialiseringsprioriteter_maxChanging(value);
                this._esas_omraadespecialiseringsprioriteter_max = value;
                this.Onesas_omraadespecialiseringsprioriteter_maxChanged();
                this.OnPropertyChanged("esas_omraadespecialiseringsprioriteter_max");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _esas_omraadespecialiseringsprioriteter_max;
        partial void Onesas_omraadespecialiseringsprioriteter_maxChanging(global::System.Nullable<int> value);
        partial void Onesas_omraadespecialiseringsprioriteter_maxChanged();
        /// <summary>
        /// There are no comments for Property esas_kot_grupper in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_kot_grupper
        {
            get
            {
                return this._esas_kot_grupper;
            }
            set
            {
                this.Onesas_kot_grupperChanging(value);
                this._esas_kot_grupper = value;
                this.Onesas_kot_grupperChanged();
                this.OnPropertyChanged("esas_kot_grupper");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_kot_grupper;
        partial void Onesas_kot_grupperChanging(string value);
        partial void Onesas_kot_grupperChanged();
        /// <summary>
        /// There are no comments for Property esas_min_kvotient in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<decimal> esas_min_kvotient
        {
            get
            {
                return this._esas_min_kvotient;
            }
            set
            {
                this.Onesas_min_kvotientChanging(value);
                this._esas_min_kvotient = value;
                this.Onesas_min_kvotientChanged();
                this.OnPropertyChanged("esas_min_kvotient");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<decimal> _esas_min_kvotient;
        partial void Onesas_min_kvotientChanging(global::System.Nullable<decimal> value);
        partial void Onesas_min_kvotientChanged();
        /// <summary>
        /// There are no comments for Property esas_navn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_navn
        {
            get
            {
                return this._esas_navn;
            }
            set
            {
                this.Onesas_navnChanging(value);
                this._esas_navn = value;
                this.Onesas_navnChanged();
                this.OnPropertyChanged("esas_navn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_navn;
        partial void Onesas_navnChanging(string value);
        partial void Onesas_navnChanged();
        /// <summary>
        /// There are no comments for Property esas_omraadenummer_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_omraadenummer_id
        {
            get
            {
                return this._esas_omraadenummer_id;
            }
            set
            {
                this.Onesas_omraadenummer_idChanging(value);
                this._esas_omraadenummer_id = value;
                this.Onesas_omraadenummer_idChanged();
                this.OnPropertyChanged("esas_omraadenummer_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_omraadenummer_id;
        partial void Onesas_omraadenummer_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_omraadenummer_idChanged();
        /// <summary>
        /// There are no comments for Property esas_studiestart_sommer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> esas_studiestart_sommer
        {
            get
            {
                return this._esas_studiestart_sommer;
            }
            set
            {
                this.Onesas_studiestart_sommerChanging(value);
                this._esas_studiestart_sommer = value;
                this.Onesas_studiestart_sommerChanged();
                this.OnPropertyChanged("esas_studiestart_sommer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _esas_studiestart_sommer;
        partial void Onesas_studiestart_sommerChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void Onesas_studiestart_sommerChanged();
        /// <summary>
        /// There are no comments for Property esas_studiestart_vinter in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> esas_studiestart_vinter
        {
            get
            {
                return this._esas_studiestart_vinter;
            }
            set
            {
                this.Onesas_studiestart_vinterChanging(value);
                this._esas_studiestart_vinter = value;
                this.Onesas_studiestart_vinterChanged();
                this.OnPropertyChanged("esas_studiestart_vinter");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _esas_studiestart_vinter;
        partial void Onesas_studiestart_vinterChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void Onesas_studiestart_vinterChanged();
        /// <summary>
        /// There are no comments for Property esas_pladstilbudssvarfrist in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> esas_pladstilbudssvarfrist
        {
            get
            {
                return this._esas_pladstilbudssvarfrist;
            }
            set
            {
                this.Onesas_pladstilbudssvarfristChanging(value);
                this._esas_pladstilbudssvarfrist = value;
                this.Onesas_pladstilbudssvarfristChanged();
                this.OnPropertyChanged("esas_pladstilbudssvarfrist");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _esas_pladstilbudssvarfrist;
        partial void Onesas_pladstilbudssvarfristChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void Onesas_pladstilbudssvarfristChanged();
        /// <summary>
        /// There are no comments for Property esas_forventet_afslutning_vinter in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> esas_forventet_afslutning_vinter
        {
            get
            {
                return this._esas_forventet_afslutning_vinter;
            }
            set
            {
                this.Onesas_forventet_afslutning_vinterChanging(value);
                this._esas_forventet_afslutning_vinter = value;
                this.Onesas_forventet_afslutning_vinterChanged();
                this.OnPropertyChanged("esas_forventet_afslutning_vinter");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _esas_forventet_afslutning_vinter;
        partial void Onesas_forventet_afslutning_vinterChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void Onesas_forventet_afslutning_vinterChanged();
        /// <summary>
        /// There are no comments for Property esas_forventet_afslutning_sommer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> esas_forventet_afslutning_sommer
        {
            get
            {
                return this._esas_forventet_afslutning_sommer;
            }
            set
            {
                this.Onesas_forventet_afslutning_sommerChanging(value);
                this._esas_forventet_afslutning_sommer = value;
                this.Onesas_forventet_afslutning_sommerChanged();
                this.OnPropertyChanged("esas_forventet_afslutning_sommer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _esas_forventet_afslutning_sommer;
        partial void Onesas_forventet_afslutning_sommerChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void Onesas_forventet_afslutning_sommerChanged();
        /// <summary>
        /// There are no comments for Property esas_ledige_standbypladser in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> esas_ledige_standbypladser
        {
            get
            {
                return this._esas_ledige_standbypladser;
            }
            set
            {
                this.Onesas_ledige_standbypladserChanging(value);
                this._esas_ledige_standbypladser = value;
                this.Onesas_ledige_standbypladserChanged();
                this.OnPropertyChanged("esas_ledige_standbypladser");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _esas_ledige_standbypladser;
        partial void Onesas_ledige_standbypladserChanging(global::System.Nullable<int> value);
        partial void Onesas_ledige_standbypladserChanged();
        /// <summary>
        /// There are no comments for Property esas_ledige_pladser_sommer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> esas_ledige_pladser_sommer
        {
            get
            {
                return this._esas_ledige_pladser_sommer;
            }
            set
            {
                this.Onesas_ledige_pladser_sommerChanging(value);
                this._esas_ledige_pladser_sommer = value;
                this.Onesas_ledige_pladser_sommerChanged();
                this.OnPropertyChanged("esas_ledige_pladser_sommer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _esas_ledige_pladser_sommer;
        partial void Onesas_ledige_pladser_sommerChanging(global::System.Nullable<int> value);
        partial void Onesas_ledige_pladser_sommerChanged();
        /// <summary>
        /// There are no comments for Property esas_ledige_pladser_vinter in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> esas_ledige_pladser_vinter
        {
            get
            {
                return this._esas_ledige_pladser_vinter;
            }
            set
            {
                this.Onesas_ledige_pladser_vinterChanging(value);
                this._esas_ledige_pladser_vinter = value;
                this.Onesas_ledige_pladser_vinterChanged();
                this.OnPropertyChanged("esas_ledige_pladser_vinter");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _esas_ledige_pladser_vinter;
        partial void Onesas_ledige_pladser_vinterChanging(global::System.Nullable<int> value);
        partial void Onesas_ledige_pladser_vinterChanged();
        /// <summary>
        /// There are no comments for Property esas_ledige_studiepladser_sommer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> esas_ledige_studiepladser_sommer
        {
            get
            {
                return this._esas_ledige_studiepladser_sommer;
            }
            set
            {
                this.Onesas_ledige_studiepladser_sommerChanging(value);
                this._esas_ledige_studiepladser_sommer = value;
                this.Onesas_ledige_studiepladser_sommerChanged();
                this.OnPropertyChanged("esas_ledige_studiepladser_sommer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _esas_ledige_studiepladser_sommer;
        partial void Onesas_ledige_studiepladser_sommerChanging(global::System.Nullable<int> value);
        partial void Onesas_ledige_studiepladser_sommerChanged();
        /// <summary>
        /// There are no comments for Property esas_ledige_studiepladser_vinter in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> esas_ledige_studiepladser_vinter
        {
            get
            {
                return this._esas_ledige_studiepladser_vinter;
            }
            set
            {
                this.Onesas_ledige_studiepladser_vinterChanging(value);
                this._esas_ledige_studiepladser_vinter = value;
                this.Onesas_ledige_studiepladser_vinterChanged();
                this.OnPropertyChanged("esas_ledige_studiepladser_vinter");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _esas_ledige_studiepladser_vinter;
        partial void Onesas_ledige_studiepladser_vinterChanging(global::System.Nullable<int> value);
        partial void Onesas_ledige_studiepladser_vinterChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _CreatedBy;
        partial void OnCreatedByChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property CreatedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> CreatedOn
        {
            get
            {
                return this._CreatedOn;
            }
            set
            {
                this.OnCreatedOnChanging(value);
                this._CreatedOn = value;
                this.OnCreatedOnChanged();
                this.OnPropertyChanged("CreatedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _CreatedOn;
        partial void OnCreatedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedOnChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _ModifiedBy;
        partial void OnModifiedByChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> ModifiedOn
        {
            get
            {
                return this._ModifiedOn;
            }
            set
            {
                this.OnModifiedOnChanging(value);
                this._ModifiedOn = value;
                this.OnModifiedOnChanged();
                this.OnPropertyChanged("ModifiedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _ModifiedOn;
        partial void OnModifiedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedOnChanged();
        /// <summary>
        /// There are no comments for Property OwningBusinessUnit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> OwningBusinessUnit
        {
            get
            {
                return this._OwningBusinessUnit;
            }
            set
            {
                this.OnOwningBusinessUnitChanging(value);
                this._OwningBusinessUnit = value;
                this.OnOwningBusinessUnitChanged();
                this.OnPropertyChanged("OwningBusinessUnit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _OwningBusinessUnit;
        partial void OnOwningBusinessUnitChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnOwningBusinessUnitChanged();
        /// <summary>
        /// There are no comments for Property statecode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> statecode
        {
            get
            {
                return this._statecode;
            }
            set
            {
                this.OnstatecodeChanging(value);
                this._statecode = value;
                this.OnstatecodeChanged();
                this.OnPropertyChanged("statecode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _statecode;
        partial void OnstatecodeChanging(global::System.Nullable<int> value);
        partial void OnstatecodeChanged();
        /// <summary>
        /// There are no comments for Property statuscode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> statuscode
        {
            get
            {
                return this._statuscode;
            }
            set
            {
                this.OnstatuscodeChanging(value);
                this._statuscode = value;
                this.OnstatuscodeChanged();
                this.OnPropertyChanged("statuscode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _statuscode;
        partial void OnstatuscodeChanging(global::System.Nullable<int> value);
        partial void OnstatuscodeChanged();
        /// <summary>
        /// There are no comments for Property esas_ansoegningsopsaetning in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.Ansoegningsopsaetning esas_ansoegningsopsaetning
        {
            get
            {
                return this._esas_ansoegningsopsaetning;
            }
            set
            {
                this.Onesas_ansoegningsopsaetningChanging(value);
                this._esas_ansoegningsopsaetning = value;
                this.Onesas_ansoegningsopsaetningChanged();
                this.OnPropertyChanged("esas_ansoegningsopsaetning");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.Ansoegningsopsaetning _esas_ansoegningsopsaetning;
        partial void Onesas_ansoegningsopsaetningChanging(global::esas.Dynamics.Models.Contracts.Ansoegningsopsaetning value);
        partial void Onesas_ansoegningsopsaetningChanged();
        /// <summary>
        /// There are no comments for Property esas_aktivitetsudbud in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.Aktivitetsudbud esas_aktivitetsudbud
        {
            get
            {
                return this._esas_aktivitetsudbud;
            }
            set
            {
                this.Onesas_aktivitetsudbudChanging(value);
                this._esas_aktivitetsudbud = value;
                this.Onesas_aktivitetsudbudChanged();
                this.OnPropertyChanged("esas_aktivitetsudbud");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.Aktivitetsudbud _esas_aktivitetsudbud;
        partial void Onesas_aktivitetsudbudChanging(global::esas.Dynamics.Models.Contracts.Aktivitetsudbud value);
        partial void Onesas_aktivitetsudbudChanged();
        /// <summary>
        /// There are no comments for Property esas_publicering in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.Publicering esas_publicering
        {
            get
            {
                return this._esas_publicering;
            }
            set
            {
                this.Onesas_publiceringChanging(value);
                this._esas_publicering = value;
                this.Onesas_publiceringChanged();
                this.OnPropertyChanged("esas_publicering");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.Publicering _esas_publicering;
        partial void Onesas_publiceringChanging(global::esas.Dynamics.Models.Contracts.Publicering value);
        partial void Onesas_publiceringChanged();
        /// <summary>
        /// There are no comments for Property esas_adgangskrav in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.Adgangskrav esas_adgangskrav
        {
            get
            {
                return this._esas_adgangskrav;
            }
            set
            {
                this.Onesas_adgangskravChanging(value);
                this._esas_adgangskrav = value;
                this.Onesas_adgangskravChanged();
                this.OnPropertyChanged("esas_adgangskrav");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.Adgangskrav _esas_adgangskrav;
        partial void Onesas_adgangskravChanging(global::esas.Dynamics.Models.Contracts.Adgangskrav value);
        partial void Onesas_adgangskravChanged();
        /// <summary>
        /// There are no comments for Property list_esas_ansoegning in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Ansoegning> list_esas_ansoegning
        {
            get
            {
                return this._list_esas_ansoegning;
            }
            set
            {
                this.Onlist_esas_ansoegningChanging(value);
                this._list_esas_ansoegning = value;
                this.Onlist_esas_ansoegningChanged();
                this.OnPropertyChanged("list_esas_ansoegning");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Ansoegning> _list_esas_ansoegning = new global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Ansoegning>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void Onlist_esas_ansoegningChanging(global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Ansoegning> value);
        partial void Onlist_esas_ansoegningChanged();
        /// <summary>
        /// There are no comments for Property list_esas_gymnasielle_fagkrav in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.GymnasielleFagkrav> list_esas_gymnasielle_fagkrav
        {
            get
            {
                return this._list_esas_gymnasielle_fagkrav;
            }
            set
            {
                this.Onlist_esas_gymnasielle_fagkravChanging(value);
                this._list_esas_gymnasielle_fagkrav = value;
                this.Onlist_esas_gymnasielle_fagkravChanged();
                this.OnPropertyChanged("list_esas_gymnasielle_fagkrav");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.GymnasielleFagkrav> _list_esas_gymnasielle_fagkrav = new global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.GymnasielleFagkrav>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void Onlist_esas_gymnasielle_fagkravChanging(global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.GymnasielleFagkrav> value);
        partial void Onlist_esas_gymnasielle_fagkravChanged();
        /// <summary>
        /// There are no comments for Property list_esas_gymnasielle_karakterkrav in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.GymnasielleKarakterkrav> list_esas_gymnasielle_karakterkrav
        {
            get
            {
                return this._list_esas_gymnasielle_karakterkrav;
            }
            set
            {
                this.Onlist_esas_gymnasielle_karakterkravChanging(value);
                this._list_esas_gymnasielle_karakterkrav = value;
                this.Onlist_esas_gymnasielle_karakterkravChanged();
                this.OnPropertyChanged("list_esas_gymnasielle_karakterkrav");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.GymnasielleKarakterkrav> _list_esas_gymnasielle_karakterkrav = new global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.GymnasielleKarakterkrav>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void Onlist_esas_gymnasielle_karakterkravChanging(global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.GymnasielleKarakterkrav> value);
        partial void Onlist_esas_gymnasielle_karakterkravChanged();
        /// <summary>
        /// There are no comments for Property list_esas_kot_gruppe in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.KOTGruppe> list_esas_kot_gruppe
        {
            get
            {
                return this._list_esas_kot_gruppe;
            }
            set
            {
                this.Onlist_esas_kot_gruppeChanging(value);
                this._list_esas_kot_gruppe = value;
                this.Onlist_esas_kot_gruppeChanged();
                this.OnPropertyChanged("list_esas_kot_gruppe");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.KOTGruppe> _list_esas_kot_gruppe = new global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.KOTGruppe>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void Onlist_esas_kot_gruppeChanging(global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.KOTGruppe> value);
        partial void Onlist_esas_kot_gruppeChanged();
        /// <summary>
        /// There are no comments for Property list_esas_omraadespecialisering in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Omraadespecialisering> list_esas_omraadespecialisering
        {
            get
            {
                return this._list_esas_omraadespecialisering;
            }
            set
            {
                this.Onlist_esas_omraadespecialiseringChanging(value);
                this._list_esas_omraadespecialisering = value;
                this.Onlist_esas_omraadespecialiseringChanged();
                this.OnPropertyChanged("list_esas_omraadespecialisering");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Omraadespecialisering> _list_esas_omraadespecialisering = new global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Omraadespecialisering>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void Onlist_esas_omraadespecialiseringChanging(global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Omraadespecialisering> value);
        partial void Onlist_esas_omraadespecialiseringChanged();
        /// <summary>
        /// There are no comments for Property list_esas_kvalifikationskriterie in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Kvalifikationskriterie> list_esas_kvalifikationskriterie
        {
            get
            {
                return this._list_esas_kvalifikationskriterie;
            }
            set
            {
                this.Onlist_esas_kvalifikationskriterieChanging(value);
                this._list_esas_kvalifikationskriterie = value;
                this.Onlist_esas_kvalifikationskriterieChanged();
                this.OnPropertyChanged("list_esas_kvalifikationskriterie");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Kvalifikationskriterie> _list_esas_kvalifikationskriterie = new global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Kvalifikationskriterie>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void Onlist_esas_kvalifikationskriterieChanging(global::Microsoft.OData.Client.DataServiceCollection<global::esas.Dynamics.Models.Contracts.Kvalifikationskriterie> value);
        partial void Onlist_esas_kvalifikationskriterieChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
