//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 03-03-2021 10:44:52
namespace esas.Dynamics.Models.Contracts
{
    /// <summary>
    /// There are no comments for VideregaaendeUddannelseSingle in the schema.
    /// </summary>
    public partial class VideregaaendeUddannelseSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<VideregaaendeUddannelse>
    {
        /// <summary>
        /// Initialize a new VideregaaendeUddannelseSingle object.
        /// </summary>
        public VideregaaendeUddannelseSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new VideregaaendeUddannelseSingle object.
        /// </summary>
        public VideregaaendeUddannelseSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new VideregaaendeUddannelseSingle object.
        /// </summary>
        public VideregaaendeUddannelseSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<VideregaaendeUddannelse> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for esas_ansoegning in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.AnsoegningSingle esas_ansoegning
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._esas_ansoegning == null))
                {
                    this._esas_ansoegning = new global::esas.Dynamics.Models.Contracts.AnsoegningSingle(this.Context, GetPath("esas_ansoegning"));
                }
                return this._esas_ansoegning;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.AnsoegningSingle _esas_ansoegning;
    }
    /// <summary>
    /// There are no comments for VideregaaendeUddannelse in the schema.
    /// </summary>
    /// <KeyProperties>
    /// esas_ansoegning_videregaaende_uddannelseid
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("esas_ansoegning_videregaaende_uddannelseid")]
    public partial class VideregaaendeUddannelse : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property esas_ansoegning_videregaaende_uddannelseid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_ansoegning_videregaaende_uddannelseid
        {
            get
            {
                return this._esas_ansoegning_videregaaende_uddannelseid;
            }
            set
            {
                this.Onesas_ansoegning_videregaaende_uddannelseidChanging(value);
                this._esas_ansoegning_videregaaende_uddannelseid = value;
                this.Onesas_ansoegning_videregaaende_uddannelseidChanged();
                this.OnPropertyChanged("esas_ansoegning_videregaaende_uddannelseid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_ansoegning_videregaaende_uddannelseid;
        partial void Onesas_ansoegning_videregaaende_uddannelseidChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_ansoegning_videregaaende_uddannelseidChanged();
        /// <summary>
        /// There are no comments for Property esas_ansoegning_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> esas_ansoegning_id
        {
            get
            {
                return this._esas_ansoegning_id;
            }
            set
            {
                this.Onesas_ansoegning_idChanging(value);
                this._esas_ansoegning_id = value;
                this.Onesas_ansoegning_idChanged();
                this.OnPropertyChanged("esas_ansoegning_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _esas_ansoegning_id;
        partial void Onesas_ansoegning_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onesas_ansoegning_idChanged();
        /// <summary>
        /// There are no comments for Property esas_navn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_navn
        {
            get
            {
                return this._esas_navn;
            }
            set
            {
                this.Onesas_navnChanging(value);
                this._esas_navn = value;
                this.Onesas_navnChanged();
                this.OnPropertyChanged("esas_navn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_navn;
        partial void Onesas_navnChanging(string value);
        partial void Onesas_navnChanged();
        /// <summary>
        /// There are no comments for Property esas_optagelsesomraadenavn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_optagelsesomraadenavn
        {
            get
            {
                return this._esas_optagelsesomraadenavn;
            }
            set
            {
                this.Onesas_optagelsesomraadenavnChanging(value);
                this._esas_optagelsesomraadenavn = value;
                this.Onesas_optagelsesomraadenavnChanged();
                this.OnPropertyChanged("esas_optagelsesomraadenavn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_optagelsesomraadenavn;
        partial void Onesas_optagelsesomraadenavnChanging(string value);
        partial void Onesas_optagelsesomraadenavnChanged();
        /// <summary>
        /// There are no comments for Property esas_institutionsnavn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_institutionsnavn
        {
            get
            {
                return this._esas_institutionsnavn;
            }
            set
            {
                this.Onesas_institutionsnavnChanging(value);
                this._esas_institutionsnavn = value;
                this.Onesas_institutionsnavnChanged();
                this.OnPropertyChanged("esas_institutionsnavn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_institutionsnavn;
        partial void Onesas_institutionsnavnChanging(string value);
        partial void Onesas_institutionsnavnChanged();
        /// <summary>
        /// There are no comments for Property esas_paabegyndt_aar in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_paabegyndt_aar
        {
            get
            {
                return this._esas_paabegyndt_aar;
            }
            set
            {
                this.Onesas_paabegyndt_aarChanging(value);
                this._esas_paabegyndt_aar = value;
                this.Onesas_paabegyndt_aarChanged();
                this.OnPropertyChanged("esas_paabegyndt_aar");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_paabegyndt_aar;
        partial void Onesas_paabegyndt_aarChanging(string value);
        partial void Onesas_paabegyndt_aarChanged();
        /// <summary>
        /// There are no comments for Property esas_bestaaet_aar in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_bestaaet_aar
        {
            get
            {
                return this._esas_bestaaet_aar;
            }
            set
            {
                this.Onesas_bestaaet_aarChanging(value);
                this._esas_bestaaet_aar = value;
                this.Onesas_bestaaet_aarChanged();
                this.OnPropertyChanged("esas_bestaaet_aar");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_bestaaet_aar;
        partial void Onesas_bestaaet_aarChanging(string value);
        partial void Onesas_bestaaet_aarChanged();
        /// <summary>
        /// There are no comments for Property esas_ects in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<decimal> esas_ects
        {
            get
            {
                return this._esas_ects;
            }
            set
            {
                this.Onesas_ectsChanging(value);
                this._esas_ects = value;
                this.Onesas_ectsChanged();
                this.OnPropertyChanged("esas_ects");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<decimal> _esas_ects;
        partial void Onesas_ectsChanging(global::System.Nullable<decimal> value);
        partial void Onesas_ectsChanged();
        /// <summary>
        /// There are no comments for Property esas_stadig_optaget in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<bool> esas_stadig_optaget
        {
            get
            {
                return this._esas_stadig_optaget;
            }
            set
            {
                this.Onesas_stadig_optagetChanging(value);
                this._esas_stadig_optaget = value;
                this.Onesas_stadig_optagetChanged();
                this.OnPropertyChanged("esas_stadig_optaget");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _esas_stadig_optaget;
        partial void Onesas_stadig_optagetChanging(global::System.Nullable<bool> value);
        partial void Onesas_stadig_optagetChanged();
        /// <summary>
        /// There are no comments for Property esas_afbrudt_aar in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string esas_afbrudt_aar
        {
            get
            {
                return this._esas_afbrudt_aar;
            }
            set
            {
                this.Onesas_afbrudt_aarChanging(value);
                this._esas_afbrudt_aar = value;
                this.Onesas_afbrudt_aarChanged();
                this.OnPropertyChanged("esas_afbrudt_aar");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _esas_afbrudt_aar;
        partial void Onesas_afbrudt_aarChanging(string value);
        partial void Onesas_afbrudt_aarChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _CreatedBy;
        partial void OnCreatedByChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property CreatedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> CreatedOn
        {
            get
            {
                return this._CreatedOn;
            }
            set
            {
                this.OnCreatedOnChanging(value);
                this._CreatedOn = value;
                this.OnCreatedOnChanged();
                this.OnPropertyChanged("CreatedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _CreatedOn;
        partial void OnCreatedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedOnChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _ModifiedBy;
        partial void OnModifiedByChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property ModifiedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> ModifiedOn
        {
            get
            {
                return this._ModifiedOn;
            }
            set
            {
                this.OnModifiedOnChanging(value);
                this._ModifiedOn = value;
                this.OnModifiedOnChanged();
                this.OnPropertyChanged("ModifiedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _ModifiedOn;
        partial void OnModifiedOnChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedOnChanged();
        /// <summary>
        /// There are no comments for Property OwningBusinessUnit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.Guid> OwningBusinessUnit
        {
            get
            {
                return this._OwningBusinessUnit;
            }
            set
            {
                this.OnOwningBusinessUnitChanging(value);
                this._OwningBusinessUnit = value;
                this.OnOwningBusinessUnitChanged();
                this.OnPropertyChanged("OwningBusinessUnit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _OwningBusinessUnit;
        partial void OnOwningBusinessUnitChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnOwningBusinessUnitChanged();
        /// <summary>
        /// There are no comments for Property statecode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> statecode
        {
            get
            {
                return this._statecode;
            }
            set
            {
                this.OnstatecodeChanging(value);
                this._statecode = value;
                this.OnstatecodeChanged();
                this.OnPropertyChanged("statecode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _statecode;
        partial void OnstatecodeChanging(global::System.Nullable<int> value);
        partial void OnstatecodeChanged();
        /// <summary>
        /// There are no comments for Property statuscode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> statuscode
        {
            get
            {
                return this._statuscode;
            }
            set
            {
                this.OnstatuscodeChanging(value);
                this._statuscode = value;
                this.OnstatuscodeChanged();
                this.OnPropertyChanged("statuscode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _statuscode;
        partial void OnstatuscodeChanging(global::System.Nullable<int> value);
        partial void OnstatuscodeChanged();
        /// <summary>
        /// There are no comments for Property esas_ansoegning in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::esas.Dynamics.Models.Contracts.Ansoegning esas_ansoegning
        {
            get
            {
                return this._esas_ansoegning;
            }
            set
            {
                this.Onesas_ansoegningChanging(value);
                this._esas_ansoegning = value;
                this.Onesas_ansoegningChanged();
                this.OnPropertyChanged("esas_ansoegning");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::esas.Dynamics.Models.Contracts.Ansoegning _esas_ansoegning;
        partial void Onesas_ansoegningChanging(global::esas.Dynamics.Models.Contracts.Ansoegning value);
        partial void Onesas_ansoegningChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
